
// This file has been generated by the GUI designer. Do not modify.
namespace punto.gui
{
	public partial class IngresarProductosDialog
	{
		private global::Gtk.Notebook notebook1;
		private global::Gtk.VBox vbox3;
		private global::Gtk.Label labelTituloRegistrarProd;
		private global::Gtk.Alignment alignment3;
		private global::Gtk.VBox vbox6;
		private global::Gtk.Table table1;
		private global::Gtk.CheckButton checkbuttonPesable;
		private global::Gtk.CheckButton checkbuttonVigente;
		private global::Gtk.ComboBox comboboxFamiliaProd;
		private global::Gtk.Entry entryCodigoBarra;
		private global::Gtk.Entry entryNombre;
		private global::Gtk.Entry entryPrecioVenta;
		private global::Gtk.Label labelCodigoBarra;
		private global::Gtk.Label labelFamilia;
		private global::Gtk.Label labelNombre;
		private global::Gtk.Label labelPrecioVenta;
		private global::Gtk.HBox hbox1;
		private global::Gtk.Label label5;
		private global::Gtk.Button BotonAgregarProd;
		private global::Gtk.Label label6;
		private global::Gtk.Label labelRegistrarProducto;
		private global::Gtk.Frame frame4;
		private global::Gtk.Alignment GtkAlignment2;
		private global::Gtk.VBox vbox4;
		private global::Gtk.HBox hbox5;
		private global::Gtk.Button BotonEditar;
		private global::Gtk.HBox hbox6;
		private global::Gtk.ScrolledWindow GtkScrolledWindow;
		private global::Gtk.TreeView treeview1;
		private global::Gtk.Label GtkLabel4;
		private global::Gtk.Label labelModificarProducto;
		private global::Gtk.Button buttonCancel;
		private global::Gtk.Button buttonOk;
		
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget punto.gui.IngresarProductosDialog
			this.Name = "punto.gui.IngresarProductosDialog";
			this.Title = global::Mono.Unix.Catalog.GetString ("Registrar / Modificar Producto");
			this.WindowPosition = ((global::Gtk.WindowPosition)(1));
			// Internal child punto.gui.IngresarProductosDialog.VBox
			global::Gtk.VBox w1 = this.VBox;
			w1.Name = "dialog1_VBox";
			w1.BorderWidth = ((uint)(2));
			// Container child dialog1_VBox.Gtk.Box+BoxChild
			this.notebook1 = new global::Gtk.Notebook ();
			this.notebook1.CanFocus = true;
			this.notebook1.Name = "notebook1";
			this.notebook1.CurrentPage = 1;
			// Container child notebook1.Gtk.Notebook+NotebookChild
			this.vbox3 = new global::Gtk.VBox ();
			this.vbox3.Name = "vbox3";
			this.vbox3.Spacing = 6;
			// Container child vbox3.Gtk.Box+BoxChild
			this.labelTituloRegistrarProd = new global::Gtk.Label ();
			this.labelTituloRegistrarProd.Name = "labelTituloRegistrarProd";
			this.labelTituloRegistrarProd.Ypad = 10;
			this.labelTituloRegistrarProd.LabelProp = global::Mono.Unix.Catalog.GetString ("Ingreso de productos de la Base de Datos");
			this.vbox3.Add (this.labelTituloRegistrarProd);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.labelTituloRegistrarProd]));
			w2.Position = 0;
			w2.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.alignment3 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
			this.alignment3.Name = "alignment3";
			// Container child alignment3.Gtk.Container+ContainerChild
			this.vbox6 = new global::Gtk.VBox ();
			this.vbox6.Name = "vbox6";
			this.vbox6.Spacing = 6;
			// Container child vbox6.Gtk.Box+BoxChild
			this.table1 = new global::Gtk.Table (((uint)(6)), ((uint)(2)), true);
			this.table1.Name = "table1";
			this.table1.RowSpacing = ((uint)(6));
			this.table1.ColumnSpacing = ((uint)(6));
			this.table1.BorderWidth = ((uint)(7));
			// Container child table1.Gtk.Table+TableChild
			this.checkbuttonPesable = new global::Gtk.CheckButton ();
			this.checkbuttonPesable.CanFocus = true;
			this.checkbuttonPesable.Name = "checkbuttonPesable";
			this.checkbuttonPesable.Label = global::Mono.Unix.Catalog.GetString ("Pesable");
			this.checkbuttonPesable.DrawIndicator = true;
			this.checkbuttonPesable.UseUnderline = true;
			this.table1.Add (this.checkbuttonPesable);
			global::Gtk.Table.TableChild w3 = ((global::Gtk.Table.TableChild)(this.table1 [this.checkbuttonPesable]));
			w3.TopAttach = ((uint)(3));
			w3.BottomAttach = ((uint)(4));
			w3.LeftAttach = ((uint)(1));
			w3.RightAttach = ((uint)(2));
			w3.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.checkbuttonVigente = new global::Gtk.CheckButton ();
			this.checkbuttonVigente.CanFocus = true;
			this.checkbuttonVigente.Name = "checkbuttonVigente";
			this.checkbuttonVigente.Label = global::Mono.Unix.Catalog.GetString ("Vigente");
			this.checkbuttonVigente.Active = true;
			this.checkbuttonVigente.DrawIndicator = true;
			this.checkbuttonVigente.UseUnderline = true;
			this.table1.Add (this.checkbuttonVigente);
			global::Gtk.Table.TableChild w4 = ((global::Gtk.Table.TableChild)(this.table1 [this.checkbuttonVigente]));
			w4.TopAttach = ((uint)(4));
			w4.BottomAttach = ((uint)(5));
			w4.LeftAttach = ((uint)(1));
			w4.RightAttach = ((uint)(2));
			w4.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.comboboxFamiliaProd = global::Gtk.ComboBox.NewText ();
			this.comboboxFamiliaProd.Name = "comboboxFamiliaProd";
			this.table1.Add (this.comboboxFamiliaProd);
			global::Gtk.Table.TableChild w5 = ((global::Gtk.Table.TableChild)(this.table1 [this.comboboxFamiliaProd]));
			w5.TopAttach = ((uint)(5));
			w5.BottomAttach = ((uint)(6));
			w5.LeftAttach = ((uint)(1));
			w5.RightAttach = ((uint)(2));
			w5.XOptions = ((global::Gtk.AttachOptions)(4));
			w5.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.entryCodigoBarra = new global::Gtk.Entry ();
			this.entryCodigoBarra.CanFocus = true;
			this.entryCodigoBarra.Name = "entryCodigoBarra";
			this.entryCodigoBarra.IsEditable = true;
			this.entryCodigoBarra.InvisibleChar = '●';
			this.table1.Add (this.entryCodigoBarra);
			global::Gtk.Table.TableChild w6 = ((global::Gtk.Table.TableChild)(this.table1 [this.entryCodigoBarra]));
			w6.LeftAttach = ((uint)(1));
			w6.RightAttach = ((uint)(2));
			w6.XOptions = ((global::Gtk.AttachOptions)(4));
			w6.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.entryNombre = new global::Gtk.Entry ();
			this.entryNombre.CanFocus = true;
			this.entryNombre.Name = "entryNombre";
			this.entryNombre.IsEditable = true;
			this.entryNombre.InvisibleChar = '●';
			this.table1.Add (this.entryNombre);
			global::Gtk.Table.TableChild w7 = ((global::Gtk.Table.TableChild)(this.table1 [this.entryNombre]));
			w7.TopAttach = ((uint)(1));
			w7.BottomAttach = ((uint)(2));
			w7.LeftAttach = ((uint)(1));
			w7.RightAttach = ((uint)(2));
			w7.XOptions = ((global::Gtk.AttachOptions)(4));
			w7.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.entryPrecioVenta = new global::Gtk.Entry ();
			this.entryPrecioVenta.CanFocus = true;
			this.entryPrecioVenta.Name = "entryPrecioVenta";
			this.entryPrecioVenta.IsEditable = true;
			this.entryPrecioVenta.InvisibleChar = '●';
			this.table1.Add (this.entryPrecioVenta);
			global::Gtk.Table.TableChild w8 = ((global::Gtk.Table.TableChild)(this.table1 [this.entryPrecioVenta]));
			w8.TopAttach = ((uint)(2));
			w8.BottomAttach = ((uint)(3));
			w8.LeftAttach = ((uint)(1));
			w8.RightAttach = ((uint)(2));
			w8.XOptions = ((global::Gtk.AttachOptions)(4));
			w8.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.labelCodigoBarra = new global::Gtk.Label ();
			this.labelCodigoBarra.Name = "labelCodigoBarra";
			this.labelCodigoBarra.Xalign = 0F;
			this.labelCodigoBarra.LabelProp = global::Mono.Unix.Catalog.GetString ("     Codigo de Barra: ");
			this.table1.Add (this.labelCodigoBarra);
			global::Gtk.Table.TableChild w9 = ((global::Gtk.Table.TableChild)(this.table1 [this.labelCodigoBarra]));
			w9.XOptions = ((global::Gtk.AttachOptions)(4));
			w9.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.labelFamilia = new global::Gtk.Label ();
			this.labelFamilia.Name = "labelFamilia";
			this.labelFamilia.Xalign = 0F;
			this.labelFamilia.LabelProp = global::Mono.Unix.Catalog.GetString ("     Familia:");
			this.table1.Add (this.labelFamilia);
			global::Gtk.Table.TableChild w10 = ((global::Gtk.Table.TableChild)(this.table1 [this.labelFamilia]));
			w10.TopAttach = ((uint)(5));
			w10.BottomAttach = ((uint)(6));
			w10.XOptions = ((global::Gtk.AttachOptions)(4));
			w10.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.labelNombre = new global::Gtk.Label ();
			this.labelNombre.Name = "labelNombre";
			this.labelNombre.Xalign = 0F;
			this.labelNombre.LabelProp = global::Mono.Unix.Catalog.GetString ("     Nombre:");
			this.table1.Add (this.labelNombre);
			global::Gtk.Table.TableChild w11 = ((global::Gtk.Table.TableChild)(this.table1 [this.labelNombre]));
			w11.TopAttach = ((uint)(1));
			w11.BottomAttach = ((uint)(2));
			w11.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.labelPrecioVenta = new global::Gtk.Label ();
			this.labelPrecioVenta.Name = "labelPrecioVenta";
			this.labelPrecioVenta.Xalign = 0F;
			this.labelPrecioVenta.LabelProp = global::Mono.Unix.Catalog.GetString ("     Precio Venta:");
			this.table1.Add (this.labelPrecioVenta);
			global::Gtk.Table.TableChild w12 = ((global::Gtk.Table.TableChild)(this.table1 [this.labelPrecioVenta]));
			w12.TopAttach = ((uint)(2));
			w12.BottomAttach = ((uint)(3));
			w12.XOptions = ((global::Gtk.AttachOptions)(4));
			w12.YOptions = ((global::Gtk.AttachOptions)(4));
			this.vbox6.Add (this.table1);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.table1]));
			w13.Position = 0;
			w13.Expand = false;
			w13.Fill = false;
			this.alignment3.Add (this.vbox6);
			this.vbox3.Add (this.alignment3);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.alignment3]));
			w15.Position = 1;
			w15.Expand = false;
			w15.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.label5 = new global::Gtk.Label ();
			this.label5.Name = "label5";
			this.label5.LabelProp = global::Mono.Unix.Catalog.GetString ("              ");
			this.hbox1.Add (this.label5);
			global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.label5]));
			w16.Position = 0;
			w16.Expand = false;
			w16.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.BotonAgregarProd = new global::Gtk.Button ();
			this.BotonAgregarProd.CanFocus = true;
			this.BotonAgregarProd.Name = "BotonAgregarProd";
			this.BotonAgregarProd.UseUnderline = true;
			this.BotonAgregarProd.Label = global::Mono.Unix.Catalog.GetString ("Agregar");
			this.hbox1.Add (this.BotonAgregarProd);
			global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.BotonAgregarProd]));
			w17.Position = 1;
			w17.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.label6 = new global::Gtk.Label ();
			this.label6.Name = "label6";
			this.label6.LabelProp = global::Mono.Unix.Catalog.GetString ("                 ");
			this.hbox1.Add (this.label6);
			global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.label6]));
			w18.Position = 3;
			w18.Expand = false;
			w18.Fill = false;
			this.vbox3.Add (this.hbox1);
			global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.hbox1]));
			w19.Position = 3;
			w19.Expand = false;
			w19.Fill = false;
			this.notebook1.Add (this.vbox3);
			// Notebook tab
			this.labelRegistrarProducto = new global::Gtk.Label ();
			this.labelRegistrarProducto.Name = "labelRegistrarProducto";
			this.labelRegistrarProducto.LabelProp = global::Mono.Unix.Catalog.GetString ("Registrar Producto");
			this.notebook1.SetTabLabel (this.vbox3, this.labelRegistrarProducto);
			this.labelRegistrarProducto.ShowAll ();
			// Container child notebook1.Gtk.Notebook+NotebookChild
			this.frame4 = new global::Gtk.Frame ();
			this.frame4.Name = "frame4";
			this.frame4.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child frame4.Gtk.Container+ContainerChild
			this.GtkAlignment2 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.GtkAlignment2.Name = "GtkAlignment2";
			this.GtkAlignment2.LeftPadding = ((uint)(12));
			// Container child GtkAlignment2.Gtk.Container+ContainerChild
			this.vbox4 = new global::Gtk.VBox ();
			this.vbox4.Name = "vbox4";
			this.vbox4.Spacing = 6;
			// Container child vbox4.Gtk.Box+BoxChild
			this.hbox5 = new global::Gtk.HBox ();
			this.hbox5.Name = "hbox5";
			this.hbox5.Spacing = 6;
			// Container child hbox5.Gtk.Box+BoxChild
			this.BotonEditar = new global::Gtk.Button ();
			this.BotonEditar.CanFocus = true;
			this.BotonEditar.Name = "BotonEditar";
			this.BotonEditar.UseUnderline = true;
			this.BotonEditar.Label = global::Mono.Unix.Catalog.GetString ("Editar");
			this.hbox5.Add (this.BotonEditar);
			global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.BotonEditar]));
			w21.Position = 1;
			w21.Expand = false;
			w21.Fill = false;
			this.vbox4.Add (this.hbox5);
			global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.hbox5]));
			w22.Position = 0;
			w22.Expand = false;
			w22.Fill = false;
			// Container child vbox4.Gtk.Box+BoxChild
			this.hbox6 = new global::Gtk.HBox ();
			this.hbox6.Name = "hbox6";
			this.hbox6.Spacing = 6;
			// Container child hbox6.Gtk.Box+BoxChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.treeview1 = new global::Gtk.TreeView ();
			this.treeview1.CanFocus = true;
			this.treeview1.Name = "treeview1";
			this.GtkScrolledWindow.Add (this.treeview1);
			this.hbox6.Add (this.GtkScrolledWindow);
			global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.GtkScrolledWindow]));
			w24.Position = 0;
			this.vbox4.Add (this.hbox6);
			global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.hbox6]));
			w25.Position = 1;
			this.GtkAlignment2.Add (this.vbox4);
			this.frame4.Add (this.GtkAlignment2);
			this.GtkLabel4 = new global::Gtk.Label ();
			this.GtkLabel4.Name = "GtkLabel4";
			this.GtkLabel4.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>GtkFrame</b>");
			this.GtkLabel4.UseMarkup = true;
			this.frame4.LabelWidget = this.GtkLabel4;
			this.notebook1.Add (this.frame4);
			global::Gtk.Notebook.NotebookChild w28 = ((global::Gtk.Notebook.NotebookChild)(this.notebook1 [this.frame4]));
			w28.Position = 1;
			// Notebook tab
			this.labelModificarProducto = new global::Gtk.Label ();
			this.labelModificarProducto.Name = "labelModificarProducto";
			this.labelModificarProducto.LabelProp = global::Mono.Unix.Catalog.GetString ("Modificar Producto");
			this.notebook1.SetTabLabel (this.frame4, this.labelModificarProducto);
			this.labelModificarProducto.ShowAll ();
			w1.Add (this.notebook1);
			global::Gtk.Box.BoxChild w29 = ((global::Gtk.Box.BoxChild)(w1 [this.notebook1]));
			w29.Position = 0;
			// Internal child punto.gui.IngresarProductosDialog.ActionArea
			global::Gtk.HButtonBox w30 = this.ActionArea;
			w30.Name = "dialog1_ActionArea";
			w30.Spacing = 10;
			w30.BorderWidth = ((uint)(5));
			w30.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(4));
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonCancel = new global::Gtk.Button ();
			this.buttonCancel.CanDefault = true;
			this.buttonCancel.CanFocus = true;
			this.buttonCancel.Name = "buttonCancel";
			this.buttonCancel.UseStock = true;
			this.buttonCancel.UseUnderline = true;
			this.buttonCancel.Label = "gtk-cancel";
			this.AddActionWidget (this.buttonCancel, -6);
			global::Gtk.ButtonBox.ButtonBoxChild w31 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w30 [this.buttonCancel]));
			w31.Expand = false;
			w31.Fill = false;
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonOk = new global::Gtk.Button ();
			this.buttonOk.CanDefault = true;
			this.buttonOk.CanFocus = true;
			this.buttonOk.Name = "buttonOk";
			this.buttonOk.UseStock = true;
			this.buttonOk.UseUnderline = true;
			this.buttonOk.Label = "gtk-ok";
			this.AddActionWidget (this.buttonOk, -5);
			global::Gtk.ButtonBox.ButtonBoxChild w32 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w30 [this.buttonOk]));
			w32.Position = 1;
			w32.Expand = false;
			w32.Fill = false;
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 437;
			this.Show ();
			this.checkbuttonVigente.Toggled += new global::System.EventHandler (this.OnCheckbutton8Toggled);
			this.checkbuttonPesable.Toggled += new global::System.EventHandler (this.OnCheckbutton7Toggled);
			this.BotonAgregarProd.Clicked += new global::System.EventHandler (this.OnBotonAgregarPClicked);
			this.BotonEditar.Clicked += new global::System.EventHandler (this.OnBotonEditarClicked);
			this.buttonOk.Clicked += new global::System.EventHandler (this.OnButtonOkClicked);
		}
	}
}
