
// This file has been generated by the GUI designer. Do not modify.
namespace punto.gui
{
	public partial class PagoTarjetaDialog
	{
		private global::Gtk.VBox vbox2;
		private global::Gtk.Frame frame1;
		private global::Gtk.Alignment GtkAlignment1;
		private global::Gtk.Table table1;
		private global::Gtk.ComboBoxEntry comboboxentryTipoTarjeta;
		private global::Gtk.Entry entryMonto;
		private global::Gtk.Entry entryNroTransaccion;
		private global::Gtk.Label labelMonto;
		private global::Gtk.Label labelNroTransacción;
		private global::Gtk.Label labelTipoTarjeta;
		private global::Gtk.Label GtkLabel1;
		private global::Gtk.Button buttonOk;
		
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget punto.gui.PagoTarjetaDialog
			this.Name = "punto.gui.PagoTarjetaDialog";
			this.Title = global::Mono.Unix.Catalog.GetString ("Pago Tarjeta");
			this.WindowPosition = ((global::Gtk.WindowPosition)(1));
			this.Resizable = false;
			// Internal child punto.gui.PagoTarjetaDialog.VBox
			global::Gtk.VBox w1 = this.VBox;
			w1.Name = "dialog1_VBox";
			w1.BorderWidth = ((uint)(2));
			// Container child dialog1_VBox.Gtk.Box+BoxChild
			this.vbox2 = new global::Gtk.VBox ();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.frame1 = new global::Gtk.Frame ();
			this.frame1.Name = "frame1";
			this.frame1.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child frame1.Gtk.Container+ContainerChild
			this.GtkAlignment1 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.GtkAlignment1.Name = "GtkAlignment1";
			this.GtkAlignment1.LeftPadding = ((uint)(12));
			// Container child GtkAlignment1.Gtk.Container+ContainerChild
			this.table1 = new global::Gtk.Table (((uint)(3)), ((uint)(4)), false);
			this.table1.Name = "table1";
			this.table1.RowSpacing = ((uint)(6));
			this.table1.ColumnSpacing = ((uint)(6));
			// Container child table1.Gtk.Table+TableChild
			this.comboboxentryTipoTarjeta = global::Gtk.ComboBoxEntry.NewText ();
			this.comboboxentryTipoTarjeta.Name = "comboboxentryTipoTarjeta";
			this.table1.Add (this.comboboxentryTipoTarjeta);
			global::Gtk.Table.TableChild w2 = ((global::Gtk.Table.TableChild)(this.table1 [this.comboboxentryTipoTarjeta]));
			w2.LeftAttach = ((uint)(2));
			w2.RightAttach = ((uint)(3));
			w2.XOptions = ((global::Gtk.AttachOptions)(4));
			w2.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.entryMonto = new global::Gtk.Entry ();
			this.entryMonto.CanFocus = true;
			this.entryMonto.Name = "entryMonto";
			this.entryMonto.IsEditable = true;
			this.entryMonto.InvisibleChar = '●';
			this.table1.Add (this.entryMonto);
			global::Gtk.Table.TableChild w3 = ((global::Gtk.Table.TableChild)(this.table1 [this.entryMonto]));
			w3.TopAttach = ((uint)(2));
			w3.BottomAttach = ((uint)(3));
			w3.LeftAttach = ((uint)(2));
			w3.RightAttach = ((uint)(3));
			w3.XOptions = ((global::Gtk.AttachOptions)(4));
			w3.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.entryNroTransaccion = new global::Gtk.Entry ();
			this.entryNroTransaccion.CanFocus = true;
			this.entryNroTransaccion.Name = "entryNroTransaccion";
			this.entryNroTransaccion.IsEditable = true;
			this.entryNroTransaccion.InvisibleChar = '●';
			this.table1.Add (this.entryNroTransaccion);
			global::Gtk.Table.TableChild w4 = ((global::Gtk.Table.TableChild)(this.table1 [this.entryNroTransaccion]));
			w4.TopAttach = ((uint)(1));
			w4.BottomAttach = ((uint)(2));
			w4.LeftAttach = ((uint)(2));
			w4.RightAttach = ((uint)(3));
			w4.XOptions = ((global::Gtk.AttachOptions)(4));
			w4.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.labelMonto = new global::Gtk.Label ();
			this.labelMonto.Name = "labelMonto";
			this.labelMonto.Xalign = 0F;
			this.labelMonto.LabelProp = global::Mono.Unix.Catalog.GetString ("Monto:");
			this.table1.Add (this.labelMonto);
			global::Gtk.Table.TableChild w5 = ((global::Gtk.Table.TableChild)(this.table1 [this.labelMonto]));
			w5.TopAttach = ((uint)(2));
			w5.BottomAttach = ((uint)(3));
			w5.LeftAttach = ((uint)(1));
			w5.RightAttach = ((uint)(2));
			w5.XOptions = ((global::Gtk.AttachOptions)(4));
			w5.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.labelNroTransacción = new global::Gtk.Label ();
			this.labelNroTransacción.Name = "labelNroTransacción";
			this.labelNroTransacción.Xalign = 0F;
			this.labelNroTransacción.LabelProp = global::Mono.Unix.Catalog.GetString ("Nro Transacción:");
			this.table1.Add (this.labelNroTransacción);
			global::Gtk.Table.TableChild w6 = ((global::Gtk.Table.TableChild)(this.table1 [this.labelNroTransacción]));
			w6.TopAttach = ((uint)(1));
			w6.BottomAttach = ((uint)(2));
			w6.LeftAttach = ((uint)(1));
			w6.RightAttach = ((uint)(2));
			w6.XOptions = ((global::Gtk.AttachOptions)(4));
			w6.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.labelTipoTarjeta = new global::Gtk.Label ();
			this.labelTipoTarjeta.Name = "labelTipoTarjeta";
			this.labelTipoTarjeta.Xalign = 0F;
			this.labelTipoTarjeta.LabelProp = global::Mono.Unix.Catalog.GetString ("Tipo Tarjeta:");
			this.table1.Add (this.labelTipoTarjeta);
			global::Gtk.Table.TableChild w7 = ((global::Gtk.Table.TableChild)(this.table1 [this.labelTipoTarjeta]));
			w7.LeftAttach = ((uint)(1));
			w7.RightAttach = ((uint)(2));
			w7.XOptions = ((global::Gtk.AttachOptions)(4));
			w7.YOptions = ((global::Gtk.AttachOptions)(4));
			this.GtkAlignment1.Add (this.table1);
			this.frame1.Add (this.GtkAlignment1);
			this.GtkLabel1 = new global::Gtk.Label ();
			this.GtkLabel1.Name = "GtkLabel1";
			this.GtkLabel1.LabelProp = global::Mono.Unix.Catalog.GetString ("Pago con Tarjeta");
			this.GtkLabel1.UseMarkup = true;
			this.frame1.LabelWidget = this.GtkLabel1;
			this.vbox2.Add (this.frame1);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.frame1]));
			w10.Position = 1;
			w10.Expand = false;
			w10.Fill = false;
			w1.Add (this.vbox2);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(w1 [this.vbox2]));
			w11.Position = 0;
			// Internal child punto.gui.PagoTarjetaDialog.ActionArea
			global::Gtk.HButtonBox w12 = this.ActionArea;
			w12.Name = "dialog1_ActionArea";
			w12.Spacing = 10;
			w12.BorderWidth = ((uint)(5));
			w12.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(4));
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonOk = new global::Gtk.Button ();
			this.buttonOk.CanDefault = true;
			this.buttonOk.CanFocus = true;
			this.buttonOk.Name = "buttonOk";
			this.buttonOk.UseStock = true;
			this.buttonOk.UseUnderline = true;
			this.buttonOk.Label = "gtk-ok";
			this.AddActionWidget (this.buttonOk, -5);
			global::Gtk.ButtonBox.ButtonBoxChild w13 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w12 [this.buttonOk]));
			w13.Expand = false;
			w13.Fill = false;
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 300;
			this.Show ();
			this.buttonOk.Clicked += new global::System.EventHandler (this.OnButtonOkClicked);
		}
	}
}
