
// This file has been generated by the GUI designer. Do not modify.
namespace punto.gui
{
	public partial class GenerarReportesDialog
	{
		private global::Gtk.VBox vbox4;
		private global::Gtk.Alignment alignment15;
		private global::Gtk.Entry entryCodigoBarra;
		private global::Gtk.Alignment alignment16;
		private global::Gtk.Button buttonGuardarReporte;
		private global::Gtk.Button buttonCancel;
		private global::Gtk.Button buttonOk;
		
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget punto.gui.GenerarReportesDialog
			this.Name = "punto.gui.GenerarReportesDialog";
			this.WindowPosition = ((global::Gtk.WindowPosition)(1));
			// Internal child punto.gui.GenerarReportesDialog.VBox
			global::Gtk.VBox w1 = this.VBox;
			w1.Name = "dialog1_VBox";
			w1.BorderWidth = ((uint)(2));
			// Container child dialog1_VBox.Gtk.Box+BoxChild
			this.vbox4 = new global::Gtk.VBox ();
			this.vbox4.Name = "vbox4";
			this.vbox4.Spacing = 6;
			// Container child vbox4.Gtk.Box+BoxChild
			this.alignment15 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
			this.alignment15.Name = "alignment15";
			this.vbox4.Add (this.alignment15);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.alignment15]));
			w2.Position = 0;
			// Container child vbox4.Gtk.Box+BoxChild
			this.entryCodigoBarra = new global::Gtk.Entry ();
			this.entryCodigoBarra.CanFocus = true;
			this.entryCodigoBarra.Name = "entryCodigoBarra";
			this.entryCodigoBarra.IsEditable = true;
			this.entryCodigoBarra.InvisibleChar = '●';
			this.vbox4.Add (this.entryCodigoBarra);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.entryCodigoBarra]));
			w3.Position = 1;
			w3.Expand = false;
			w3.Fill = false;
			// Container child vbox4.Gtk.Box+BoxChild
			this.alignment16 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
			this.alignment16.Name = "alignment16";
			// Container child alignment16.Gtk.Container+ContainerChild
			this.buttonGuardarReporte = new global::Gtk.Button ();
			this.buttonGuardarReporte.CanFocus = true;
			this.buttonGuardarReporte.Name = "buttonGuardarReporte";
			this.buttonGuardarReporte.UseUnderline = true;
			this.buttonGuardarReporte.Label = global::Mono.Unix.Catalog.GetString ("Guardar Reporte");
			this.alignment16.Add (this.buttonGuardarReporte);
			this.vbox4.Add (this.alignment16);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.alignment16]));
			w5.Position = 2;
			w5.Expand = false;
			w5.Fill = false;
			w1.Add (this.vbox4);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(w1 [this.vbox4]));
			w6.Position = 0;
			// Internal child punto.gui.GenerarReportesDialog.ActionArea
			global::Gtk.HButtonBox w7 = this.ActionArea;
			w7.Name = "dialog1_ActionArea";
			w7.Spacing = 10;
			w7.BorderWidth = ((uint)(5));
			w7.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(4));
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonCancel = new global::Gtk.Button ();
			this.buttonCancel.CanDefault = true;
			this.buttonCancel.CanFocus = true;
			this.buttonCancel.Name = "buttonCancel";
			this.buttonCancel.UseStock = true;
			this.buttonCancel.UseUnderline = true;
			this.buttonCancel.Label = "gtk-cancel";
			this.AddActionWidget (this.buttonCancel, -6);
			global::Gtk.ButtonBox.ButtonBoxChild w8 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w7 [this.buttonCancel]));
			w8.Expand = false;
			w8.Fill = false;
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonOk = new global::Gtk.Button ();
			this.buttonOk.CanDefault = true;
			this.buttonOk.CanFocus = true;
			this.buttonOk.Name = "buttonOk";
			this.buttonOk.UseStock = true;
			this.buttonOk.UseUnderline = true;
			this.buttonOk.Label = "gtk-ok";
			this.AddActionWidget (this.buttonOk, -5);
			global::Gtk.ButtonBox.ButtonBoxChild w9 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w7 [this.buttonOk]));
			w9.Position = 1;
			w9.Expand = false;
			w9.Fill = false;
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 300;
			this.Show ();
			this.buttonGuardarReporte.Clicked += new global::System.EventHandler (this.OnButtonGuardarReporteClicked);
		}
	}
}
