
// This file has been generated by the GUI designer. Do not modify.
namespace punto.gui
{
	public partial class PrincipalWindow
	{
		private global::Gtk.UIManager UIManager;
		private global::Gtk.Action ProductosAction;
		private global::Gtk.Action AgregarFamiliaAction;
		private global::Gtk.Action SesionAction;
		private global::Gtk.Action RegistrarModificarAction;
		private global::Gtk.Action CerrarAction;
		private global::Gtk.Action InicioSesionAction;
		private global::Gtk.VBox vbox3;
		private global::Gtk.MenuBar menubar1;
		private global::Gtk.HBox hbox3;
		private global::Gtk.VPaned vpaned2;
		private global::Gtk.HPaned hpaned14;
		private global::Gtk.VBox vbox4;
		private global::Gtk.Button button27;
		private global::Gtk.HPaned hpaned15;
		private global::Gtk.Label label1;
		
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget punto.gui.PrincipalWindow
			this.UIManager = new global::Gtk.UIManager ();
			global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup ("Default");
			this.ProductosAction = new global::Gtk.Action ("ProductosAction", global::Mono.Unix.Catalog.GetString ("Productos"), null, null);
			this.ProductosAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Productos");
			w1.Add (this.ProductosAction, null);
			this.AgregarFamiliaAction = new global::Gtk.Action ("AgregarFamiliaAction", global::Mono.Unix.Catalog.GetString ("Agregar Familia"), null, null);
			this.AgregarFamiliaAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Familia de productos");
			w1.Add (this.AgregarFamiliaAction, null);
			this.SesionAction = new global::Gtk.Action ("SesionAction", global::Mono.Unix.Catalog.GetString ("Sesion"), null, null);
			this.SesionAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Sesion");
			w1.Add (this.SesionAction, null);
			this.RegistrarModificarAction = new global::Gtk.Action ("RegistrarModificarAction", global::Mono.Unix.Catalog.GetString ("Registrar/Modificar"), null, null);
			this.RegistrarModificarAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Ingresar/Modificar");
			w1.Add (this.RegistrarModificarAction, null);
			this.CerrarAction = new global::Gtk.Action ("CerrarAction", global::Mono.Unix.Catalog.GetString ("Cerrar"), null, null);
			this.CerrarAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Cerrar");
			w1.Add (this.CerrarAction, null);
			this.InicioSesionAction = new global::Gtk.Action ("InicioSesionAction", global::Mono.Unix.Catalog.GetString ("Inicio Sesion"), null, null);
			this.InicioSesionAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Inicio Sesion");
			w1.Add (this.InicioSesionAction, null);
			this.UIManager.InsertActionGroup (w1, 0);
			this.AddAccelGroup (this.UIManager.AccelGroup);
			this.Name = "punto.gui.PrincipalWindow";
			this.Title = global::Mono.Unix.Catalog.GetString ("MiniMarket \"El Coke\"");
			this.WindowPosition = ((global::Gtk.WindowPosition)(1));
			// Container child punto.gui.PrincipalWindow.Gtk.Container+ContainerChild
			this.vbox3 = new global::Gtk.VBox ();
			this.vbox3.Name = "vbox3";
			this.vbox3.Spacing = 6;
			// Container child vbox3.Gtk.Box+BoxChild
			this.UIManager.AddUiFromString ("<ui><menubar name='menubar1'><menu name='SesionAction' action='SesionAction'><menuitem name='InicioSesionAction' action='InicioSesionAction'/><menuitem name='CerrarAction' action='CerrarAction'/></menu><menu name='ProductosAction' action='ProductosAction'><menuitem name='AgregarFamiliaAction' action='AgregarFamiliaAction'/><menuitem name='RegistrarModificarAction' action='RegistrarModificarAction'/></menu></menubar></ui>");
			this.menubar1 = ((global::Gtk.MenuBar)(this.UIManager.GetWidget ("/menubar1")));
			this.menubar1.Name = "menubar1";
			this.vbox3.Add (this.menubar1);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.menubar1]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.hbox3 = new global::Gtk.HBox ();
			this.hbox3.Name = "hbox3";
			this.hbox3.Spacing = 6;
			// Container child hbox3.Gtk.Box+BoxChild
			this.vpaned2 = new global::Gtk.VPaned ();
			this.vpaned2.CanFocus = true;
			this.vpaned2.Name = "vpaned2";
			this.vpaned2.Position = 10;
			// Container child vpaned2.Gtk.Paned+PanedChild
			this.hpaned14 = new global::Gtk.HPaned ();
			this.hpaned14.CanFocus = true;
			this.hpaned14.Name = "hpaned14";
			this.hpaned14.Position = 10;
			// Container child hpaned14.Gtk.Paned+PanedChild
			this.vbox4 = new global::Gtk.VBox ();
			this.vbox4.Name = "vbox4";
			this.vbox4.Spacing = 6;
			// Container child vbox4.Gtk.Box+BoxChild
			this.button27 = new global::Gtk.Button ();
			this.button27.CanFocus = true;
			this.button27.Name = "button27";
			this.button27.UseUnderline = true;
			this.button27.Label = global::Mono.Unix.Catalog.GetString ("VENDER");
			this.vbox4.Add (this.button27);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.button27]));
			w3.Position = 0;
			w3.Expand = false;
			w3.Fill = false;
			this.hpaned14.Add (this.vbox4);
			this.vpaned2.Add (this.hpaned14);
			this.hbox3.Add (this.vpaned2);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.vpaned2]));
			w6.Position = 0;
			// Container child hbox3.Gtk.Box+BoxChild
			this.hpaned15 = new global::Gtk.HPaned ();
			this.hpaned15.CanFocus = true;
			this.hpaned15.Name = "hpaned15";
			this.hpaned15.Position = 1;
			// Container child hpaned15.Gtk.Paned+PanedChild
			this.label1 = new global::Gtk.Label ();
			this.label1.Name = "label1";
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("label1");
			this.hpaned15.Add (this.label1);
			this.hbox3.Add (this.hpaned15);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.hpaned15]));
			w8.Position = 1;
			this.vbox3.Add (this.hbox3);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.hbox3]));
			w9.Position = 1;
			this.Add (this.vbox3);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 731;
			this.DefaultHeight = 479;
			this.Show ();
			this.AgregarFamiliaAction.Activated += new global::System.EventHandler (this.OnFamiliaDeProductosActionActivated);
			this.RegistrarModificarAction.Activated += new global::System.EventHandler (this.OnIngresarModificarProductosActionActivated);
			this.InicioSesionAction.Activated += new global::System.EventHandler (this.OnIniciarSesionActionActivated);
			this.button27.Clicked += new global::System.EventHandler (this.OnButton27Clicked);
		}
	}
}
