
// This file has been generated by the GUI designer. Do not modify.
namespace punto.gui
{
	public partial class IngresarProductosDialog
	{
		private global::Gtk.Notebook notebook1;
		private global::Gtk.VBox vbox3;
		private global::Gtk.Label labelTituloRegistrarProd;
		private global::Gtk.Alignment alignment3;
		private global::Gtk.VBox vbox6;
		private global::Gtk.Table table1;
		private global::Gtk.CheckButton checkbuttonPesable;
		private global::Gtk.CheckButton checkbuttonVigente;
		private global::Gtk.ComboBox comboboxFamiliaProd;
		private global::Gtk.Entry entryCodigoBarra;
		private global::Gtk.Entry entryNombre;
		private global::Gtk.Entry entryPrecioVenta;
		private global::Gtk.Label labelCodigoBarra;
		private global::Gtk.Label labelFamilia;
		private global::Gtk.Label labelNombre;
		private global::Gtk.Label labelPrecioVenta;
		private global::Gtk.HBox hbox1;
		private global::Gtk.Label label5;
		private global::Gtk.Button BotonAgregarProd;
		private global::Gtk.Label label6;
		private global::Gtk.Label labelRegistrarProducto;
		private global::Gtk.VBox vbox4;
		private global::Gtk.Label labelTituloModificarProd;
		private global::Gtk.Alignment alignment4;
		private global::Gtk.VBox vbox7;
		private global::Gtk.Table table2;
		private global::Gtk.Button BotonAgregarCambios;
		private global::Gtk.Button buttonBuscar;
		private global::Gtk.CheckButton checkbuttonVigenteMod;
		private global::Gtk.Entry entryCodigoBarraMod;
		private global::Gtk.Entry entryPrecioVentaMod;
		private global::Gtk.Label labelCodigoBarraMod;
		private global::Gtk.Label labelPrecioVentaMod;
		private global::Gtk.HBox hbox2;
		private global::Gtk.Label labelModificarProducto;
		private global::Gtk.Button buttonCancel;
		private global::Gtk.Button buttonOk;
		
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget punto.gui.IngresarProductosDialog
			this.Name = "punto.gui.IngresarProductosDialog";
			this.Title = global::Mono.Unix.Catalog.GetString ("Registrar / Modificar Producto");
			this.WindowPosition = ((global::Gtk.WindowPosition)(1));
			// Internal child punto.gui.IngresarProductosDialog.VBox
			global::Gtk.VBox w1 = this.VBox;
			w1.Name = "dialog1_VBox";
			w1.BorderWidth = ((uint)(2));
			// Container child dialog1_VBox.Gtk.Box+BoxChild
			this.notebook1 = new global::Gtk.Notebook ();
			this.notebook1.CanFocus = true;
			this.notebook1.Name = "notebook1";
			this.notebook1.CurrentPage = 1;
			// Container child notebook1.Gtk.Notebook+NotebookChild
			this.vbox3 = new global::Gtk.VBox ();
			this.vbox3.Name = "vbox3";
			this.vbox3.Spacing = 6;
			// Container child vbox3.Gtk.Box+BoxChild
			this.labelTituloRegistrarProd = new global::Gtk.Label ();
			this.labelTituloRegistrarProd.Name = "labelTituloRegistrarProd";
			this.labelTituloRegistrarProd.Ypad = 10;
			this.labelTituloRegistrarProd.LabelProp = global::Mono.Unix.Catalog.GetString ("Ingreso de productos de la Base de Datos");
			this.vbox3.Add (this.labelTituloRegistrarProd);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.labelTituloRegistrarProd]));
			w2.Position = 0;
			w2.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.alignment3 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
			this.alignment3.Name = "alignment3";
			// Container child alignment3.Gtk.Container+ContainerChild
			this.vbox6 = new global::Gtk.VBox ();
			this.vbox6.Name = "vbox6";
			this.vbox6.Spacing = 6;
			// Container child vbox6.Gtk.Box+BoxChild
			this.table1 = new global::Gtk.Table (((uint)(6)), ((uint)(2)), true);
			this.table1.Name = "table1";
			this.table1.RowSpacing = ((uint)(6));
			this.table1.ColumnSpacing = ((uint)(6));
			this.table1.BorderWidth = ((uint)(7));
			// Container child table1.Gtk.Table+TableChild
			this.checkbuttonPesable = new global::Gtk.CheckButton ();
			this.checkbuttonPesable.CanFocus = true;
			this.checkbuttonPesable.Name = "checkbuttonPesable";
			this.checkbuttonPesable.Label = global::Mono.Unix.Catalog.GetString ("Pesable");
			this.checkbuttonPesable.DrawIndicator = true;
			this.checkbuttonPesable.UseUnderline = true;
			this.table1.Add (this.checkbuttonPesable);
			global::Gtk.Table.TableChild w3 = ((global::Gtk.Table.TableChild)(this.table1 [this.checkbuttonPesable]));
			w3.TopAttach = ((uint)(3));
			w3.BottomAttach = ((uint)(4));
			w3.LeftAttach = ((uint)(1));
			w3.RightAttach = ((uint)(2));
			w3.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.checkbuttonVigente = new global::Gtk.CheckButton ();
			this.checkbuttonVigente.CanFocus = true;
			this.checkbuttonVigente.Name = "checkbuttonVigente";
			this.checkbuttonVigente.Label = global::Mono.Unix.Catalog.GetString ("Vigente");
			this.checkbuttonVigente.Active = true;
			this.checkbuttonVigente.DrawIndicator = true;
			this.checkbuttonVigente.UseUnderline = true;
			this.table1.Add (this.checkbuttonVigente);
			global::Gtk.Table.TableChild w4 = ((global::Gtk.Table.TableChild)(this.table1 [this.checkbuttonVigente]));
			w4.TopAttach = ((uint)(4));
			w4.BottomAttach = ((uint)(5));
			w4.LeftAttach = ((uint)(1));
			w4.RightAttach = ((uint)(2));
			w4.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.comboboxFamiliaProd = global::Gtk.ComboBox.NewText ();
			this.comboboxFamiliaProd.Name = "comboboxFamiliaProd";
			this.table1.Add (this.comboboxFamiliaProd);
			global::Gtk.Table.TableChild w5 = ((global::Gtk.Table.TableChild)(this.table1 [this.comboboxFamiliaProd]));
			w5.TopAttach = ((uint)(5));
			w5.BottomAttach = ((uint)(6));
			w5.LeftAttach = ((uint)(1));
			w5.RightAttach = ((uint)(2));
			w5.XOptions = ((global::Gtk.AttachOptions)(4));
			w5.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.entryCodigoBarra = new global::Gtk.Entry ();
			this.entryCodigoBarra.CanFocus = true;
			this.entryCodigoBarra.Name = "entryCodigoBarra";
			this.entryCodigoBarra.IsEditable = true;
			this.entryCodigoBarra.InvisibleChar = '●';
			this.table1.Add (this.entryCodigoBarra);
			global::Gtk.Table.TableChild w6 = ((global::Gtk.Table.TableChild)(this.table1 [this.entryCodigoBarra]));
			w6.LeftAttach = ((uint)(1));
			w6.RightAttach = ((uint)(2));
			w6.XOptions = ((global::Gtk.AttachOptions)(4));
			w6.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.entryNombre = new global::Gtk.Entry ();
			this.entryNombre.CanFocus = true;
			this.entryNombre.Name = "entryNombre";
			this.entryNombre.IsEditable = true;
			this.entryNombre.InvisibleChar = '●';
			this.table1.Add (this.entryNombre);
			global::Gtk.Table.TableChild w7 = ((global::Gtk.Table.TableChild)(this.table1 [this.entryNombre]));
			w7.TopAttach = ((uint)(1));
			w7.BottomAttach = ((uint)(2));
			w7.LeftAttach = ((uint)(1));
			w7.RightAttach = ((uint)(2));
			w7.XOptions = ((global::Gtk.AttachOptions)(4));
			w7.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.entryPrecioVenta = new global::Gtk.Entry ();
			this.entryPrecioVenta.CanFocus = true;
			this.entryPrecioVenta.Name = "entryPrecioVenta";
			this.entryPrecioVenta.IsEditable = true;
			this.entryPrecioVenta.InvisibleChar = '●';
			this.table1.Add (this.entryPrecioVenta);
			global::Gtk.Table.TableChild w8 = ((global::Gtk.Table.TableChild)(this.table1 [this.entryPrecioVenta]));
			w8.TopAttach = ((uint)(2));
			w8.BottomAttach = ((uint)(3));
			w8.LeftAttach = ((uint)(1));
			w8.RightAttach = ((uint)(2));
			w8.XOptions = ((global::Gtk.AttachOptions)(4));
			w8.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.labelCodigoBarra = new global::Gtk.Label ();
			this.labelCodigoBarra.Name = "labelCodigoBarra";
			this.labelCodigoBarra.Xalign = 0F;
			this.labelCodigoBarra.LabelProp = global::Mono.Unix.Catalog.GetString ("     Codigo de Barra: ");
			this.table1.Add (this.labelCodigoBarra);
			global::Gtk.Table.TableChild w9 = ((global::Gtk.Table.TableChild)(this.table1 [this.labelCodigoBarra]));
			w9.XOptions = ((global::Gtk.AttachOptions)(4));
			w9.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.labelFamilia = new global::Gtk.Label ();
			this.labelFamilia.Name = "labelFamilia";
			this.labelFamilia.Xalign = 0F;
			this.labelFamilia.LabelProp = global::Mono.Unix.Catalog.GetString ("     Familia:");
			this.table1.Add (this.labelFamilia);
			global::Gtk.Table.TableChild w10 = ((global::Gtk.Table.TableChild)(this.table1 [this.labelFamilia]));
			w10.TopAttach = ((uint)(5));
			w10.BottomAttach = ((uint)(6));
			w10.XOptions = ((global::Gtk.AttachOptions)(4));
			w10.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.labelNombre = new global::Gtk.Label ();
			this.labelNombre.Name = "labelNombre";
			this.labelNombre.Xalign = 0F;
			this.labelNombre.LabelProp = global::Mono.Unix.Catalog.GetString ("     Nombre:");
			this.table1.Add (this.labelNombre);
			global::Gtk.Table.TableChild w11 = ((global::Gtk.Table.TableChild)(this.table1 [this.labelNombre]));
			w11.TopAttach = ((uint)(1));
			w11.BottomAttach = ((uint)(2));
			w11.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.labelPrecioVenta = new global::Gtk.Label ();
			this.labelPrecioVenta.Name = "labelPrecioVenta";
			this.labelPrecioVenta.Xalign = 0F;
			this.labelPrecioVenta.LabelProp = global::Mono.Unix.Catalog.GetString ("     Precio Venta:");
			this.table1.Add (this.labelPrecioVenta);
			global::Gtk.Table.TableChild w12 = ((global::Gtk.Table.TableChild)(this.table1 [this.labelPrecioVenta]));
			w12.TopAttach = ((uint)(2));
			w12.BottomAttach = ((uint)(3));
			w12.XOptions = ((global::Gtk.AttachOptions)(4));
			w12.YOptions = ((global::Gtk.AttachOptions)(4));
			this.vbox6.Add (this.table1);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.table1]));
			w13.Position = 0;
			w13.Expand = false;
			w13.Fill = false;
			this.alignment3.Add (this.vbox6);
			this.vbox3.Add (this.alignment3);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.alignment3]));
			w15.Position = 1;
			w15.Expand = false;
			w15.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.label5 = new global::Gtk.Label ();
			this.label5.Name = "label5";
			this.label5.LabelProp = global::Mono.Unix.Catalog.GetString ("              ");
			this.hbox1.Add (this.label5);
			global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.label5]));
			w16.Position = 0;
			w16.Expand = false;
			w16.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.BotonAgregarProd = new global::Gtk.Button ();
			this.BotonAgregarProd.CanFocus = true;
			this.BotonAgregarProd.Name = "BotonAgregarProd";
			this.BotonAgregarProd.UseUnderline = true;
			this.BotonAgregarProd.Label = global::Mono.Unix.Catalog.GetString ("Agregar");
			this.hbox1.Add (this.BotonAgregarProd);
			global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.BotonAgregarProd]));
			w17.Position = 1;
			w17.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.label6 = new global::Gtk.Label ();
			this.label6.Name = "label6";
			this.label6.LabelProp = global::Mono.Unix.Catalog.GetString ("                 ");
			this.hbox1.Add (this.label6);
			global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.label6]));
			w18.Position = 3;
			w18.Expand = false;
			w18.Fill = false;
			this.vbox3.Add (this.hbox1);
			global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.hbox1]));
			w19.Position = 3;
			w19.Expand = false;
			w19.Fill = false;
			this.notebook1.Add (this.vbox3);
			// Notebook tab
			this.labelRegistrarProducto = new global::Gtk.Label ();
			this.labelRegistrarProducto.Name = "labelRegistrarProducto";
			this.labelRegistrarProducto.LabelProp = global::Mono.Unix.Catalog.GetString ("Registrar Producto");
			this.notebook1.SetTabLabel (this.vbox3, this.labelRegistrarProducto);
			this.labelRegistrarProducto.ShowAll ();
			// Container child notebook1.Gtk.Notebook+NotebookChild
			this.vbox4 = new global::Gtk.VBox ();
			this.vbox4.Name = "vbox4";
			this.vbox4.Spacing = 6;
			// Container child vbox4.Gtk.Box+BoxChild
			this.labelTituloModificarProd = new global::Gtk.Label ();
			this.labelTituloModificarProd.Name = "labelTituloModificarProd";
			this.labelTituloModificarProd.Ypad = 10;
			this.labelTituloModificarProd.LabelProp = global::Mono.Unix.Catalog.GetString ("Modificar productos de la Base de Datos");
			this.vbox4.Add (this.labelTituloModificarProd);
			global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.labelTituloModificarProd]));
			w21.Position = 0;
			w21.Fill = false;
			// Container child vbox4.Gtk.Box+BoxChild
			this.alignment4 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
			this.alignment4.Name = "alignment4";
			// Container child alignment4.Gtk.Container+ContainerChild
			this.vbox7 = new global::Gtk.VBox ();
			this.vbox7.Name = "vbox7";
			this.vbox7.Spacing = 6;
			// Container child vbox7.Gtk.Box+BoxChild
			this.table2 = new global::Gtk.Table (((uint)(6)), ((uint)(2)), true);
			this.table2.Name = "table2";
			this.table2.RowSpacing = ((uint)(6));
			this.table2.ColumnSpacing = ((uint)(6));
			this.table2.BorderWidth = ((uint)(7));
			// Container child table2.Gtk.Table+TableChild
			this.BotonAgregarCambios = new global::Gtk.Button ();
			this.BotonAgregarCambios.CanFocus = true;
			this.BotonAgregarCambios.Name = "BotonAgregarCambios";
			this.BotonAgregarCambios.UseUnderline = true;
			this.BotonAgregarCambios.Label = global::Mono.Unix.Catalog.GetString ("Guardar Cambios");
			this.table2.Add (this.BotonAgregarCambios);
			global::Gtk.Table.TableChild w22 = ((global::Gtk.Table.TableChild)(this.table2 [this.BotonAgregarCambios]));
			w22.TopAttach = ((uint)(5));
			w22.BottomAttach = ((uint)(6));
			w22.LeftAttach = ((uint)(1));
			w22.RightAttach = ((uint)(2));
			w22.XOptions = ((global::Gtk.AttachOptions)(0));
			w22.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.buttonBuscar = new global::Gtk.Button ();
			this.buttonBuscar.CanFocus = true;
			this.buttonBuscar.Name = "buttonBuscar";
			this.buttonBuscar.UseUnderline = true;
			this.buttonBuscar.Label = global::Mono.Unix.Catalog.GetString ("Buscar");
			this.table2.Add (this.buttonBuscar);
			global::Gtk.Table.TableChild w23 = ((global::Gtk.Table.TableChild)(this.table2 [this.buttonBuscar]));
			w23.TopAttach = ((uint)(1));
			w23.BottomAttach = ((uint)(2));
			w23.LeftAttach = ((uint)(1));
			w23.RightAttach = ((uint)(2));
			w23.XOptions = ((global::Gtk.AttachOptions)(1));
			// Container child table2.Gtk.Table+TableChild
			this.checkbuttonVigenteMod = new global::Gtk.CheckButton ();
			this.checkbuttonVigenteMod.CanFocus = true;
			this.checkbuttonVigenteMod.Name = "checkbuttonVigenteMod";
			this.checkbuttonVigenteMod.Label = global::Mono.Unix.Catalog.GetString ("Vigente");
			this.checkbuttonVigenteMod.DrawIndicator = true;
			this.checkbuttonVigenteMod.UseUnderline = true;
			this.table2.Add (this.checkbuttonVigenteMod);
			global::Gtk.Table.TableChild w24 = ((global::Gtk.Table.TableChild)(this.table2 [this.checkbuttonVigenteMod]));
			w24.TopAttach = ((uint)(4));
			w24.BottomAttach = ((uint)(5));
			w24.LeftAttach = ((uint)(1));
			w24.RightAttach = ((uint)(2));
			w24.XOptions = ((global::Gtk.AttachOptions)(4));
			w24.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.entryCodigoBarraMod = new global::Gtk.Entry ();
			this.entryCodigoBarraMod.CanFocus = true;
			this.entryCodigoBarraMod.Name = "entryCodigoBarraMod";
			this.entryCodigoBarraMod.IsEditable = true;
			this.entryCodigoBarraMod.InvisibleChar = '●';
			this.table2.Add (this.entryCodigoBarraMod);
			global::Gtk.Table.TableChild w25 = ((global::Gtk.Table.TableChild)(this.table2 [this.entryCodigoBarraMod]));
			w25.LeftAttach = ((uint)(1));
			w25.RightAttach = ((uint)(2));
			w25.XOptions = ((global::Gtk.AttachOptions)(4));
			w25.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.entryPrecioVentaMod = new global::Gtk.Entry ();
			this.entryPrecioVentaMod.CanFocus = true;
			this.entryPrecioVentaMod.Name = "entryPrecioVentaMod";
			this.entryPrecioVentaMod.IsEditable = true;
			this.entryPrecioVentaMod.InvisibleChar = '●';
			this.table2.Add (this.entryPrecioVentaMod);
			global::Gtk.Table.TableChild w26 = ((global::Gtk.Table.TableChild)(this.table2 [this.entryPrecioVentaMod]));
			w26.TopAttach = ((uint)(3));
			w26.BottomAttach = ((uint)(4));
			w26.LeftAttach = ((uint)(1));
			w26.RightAttach = ((uint)(2));
			w26.XOptions = ((global::Gtk.AttachOptions)(4));
			w26.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.labelCodigoBarraMod = new global::Gtk.Label ();
			this.labelCodigoBarraMod.Name = "labelCodigoBarraMod";
			this.labelCodigoBarraMod.LabelProp = global::Mono.Unix.Catalog.GetString ("Código Barra:");
			this.table2.Add (this.labelCodigoBarraMod);
			global::Gtk.Table.TableChild w27 = ((global::Gtk.Table.TableChild)(this.table2 [this.labelCodigoBarraMod]));
			w27.XOptions = ((global::Gtk.AttachOptions)(4));
			w27.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.labelPrecioVentaMod = new global::Gtk.Label ();
			this.labelPrecioVentaMod.Name = "labelPrecioVentaMod";
			this.labelPrecioVentaMod.LabelProp = global::Mono.Unix.Catalog.GetString ("Precio Venta:");
			this.table2.Add (this.labelPrecioVentaMod);
			global::Gtk.Table.TableChild w28 = ((global::Gtk.Table.TableChild)(this.table2 [this.labelPrecioVentaMod]));
			w28.TopAttach = ((uint)(3));
			w28.BottomAttach = ((uint)(4));
			w28.XOptions = ((global::Gtk.AttachOptions)(1));
			w28.YOptions = ((global::Gtk.AttachOptions)(4));
			this.vbox7.Add (this.table2);
			global::Gtk.Box.BoxChild w29 = ((global::Gtk.Box.BoxChild)(this.vbox7 [this.table2]));
			w29.Position = 0;
			this.alignment4.Add (this.vbox7);
			this.vbox4.Add (this.alignment4);
			global::Gtk.Box.BoxChild w31 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.alignment4]));
			w31.Position = 1;
			// Container child vbox4.Gtk.Box+BoxChild
			this.hbox2 = new global::Gtk.HBox ();
			this.hbox2.Name = "hbox2";
			this.hbox2.Spacing = 6;
			this.vbox4.Add (this.hbox2);
			global::Gtk.Box.BoxChild w32 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.hbox2]));
			w32.Position = 2;
			this.notebook1.Add (this.vbox4);
			global::Gtk.Notebook.NotebookChild w33 = ((global::Gtk.Notebook.NotebookChild)(this.notebook1 [this.vbox4]));
			w33.Position = 1;
			// Notebook tab
			this.labelModificarProducto = new global::Gtk.Label ();
			this.labelModificarProducto.Name = "labelModificarProducto";
			this.labelModificarProducto.LabelProp = global::Mono.Unix.Catalog.GetString ("Modificar Producto");
			this.notebook1.SetTabLabel (this.vbox4, this.labelModificarProducto);
			this.labelModificarProducto.ShowAll ();
			w1.Add (this.notebook1);
			global::Gtk.Box.BoxChild w34 = ((global::Gtk.Box.BoxChild)(w1 [this.notebook1]));
			w34.Position = 0;
			// Internal child punto.gui.IngresarProductosDialog.ActionArea
			global::Gtk.HButtonBox w35 = this.ActionArea;
			w35.Name = "dialog1_ActionArea";
			w35.Spacing = 10;
			w35.BorderWidth = ((uint)(5));
			w35.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(4));
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonCancel = new global::Gtk.Button ();
			this.buttonCancel.CanDefault = true;
			this.buttonCancel.CanFocus = true;
			this.buttonCancel.Name = "buttonCancel";
			this.buttonCancel.UseStock = true;
			this.buttonCancel.UseUnderline = true;
			this.buttonCancel.Label = "gtk-cancel";
			this.AddActionWidget (this.buttonCancel, -6);
			global::Gtk.ButtonBox.ButtonBoxChild w36 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w35 [this.buttonCancel]));
			w36.Expand = false;
			w36.Fill = false;
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonOk = new global::Gtk.Button ();
			this.buttonOk.CanDefault = true;
			this.buttonOk.CanFocus = true;
			this.buttonOk.Name = "buttonOk";
			this.buttonOk.UseStock = true;
			this.buttonOk.UseUnderline = true;
			this.buttonOk.Label = "gtk-ok";
			this.AddActionWidget (this.buttonOk, -5);
			global::Gtk.ButtonBox.ButtonBoxChild w37 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w35 [this.buttonOk]));
			w37.Position = 1;
			w37.Expand = false;
			w37.Fill = false;
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 437;
			this.Show ();
			this.checkbuttonVigente.Toggled += new global::System.EventHandler (this.OnCheckbutton8Toggled);
			this.checkbuttonPesable.Toggled += new global::System.EventHandler (this.OnCheckbutton7Toggled);
			this.BotonAgregarProd.Clicked += new global::System.EventHandler (this.OnBotonAgregarPClicked);
			this.checkbuttonVigenteMod.Toggled += new global::System.EventHandler (this.OnCheckbutton9Toggled);
			this.buttonBuscar.Clicked += new global::System.EventHandler (this.OnButton65Clicked);
			this.BotonAgregarCambios.Clicked += new global::System.EventHandler (this.OnBotonAgregarP1Clicked);
		}
	}
}
