
// This file has been generated by the GUI designer. Do not modify.
namespace punto.gui
{
	public partial class ConsultaPrecioDialog
	{
		private global::Gtk.Table table2;
		private global::Gtk.Entry entryCodigoDeBarra;
		private global::Gtk.HPaned hpaned4;
		private global::Gtk.Label labelConsulta;
		private global::Gtk.HPaned hpaned5;
		private global::Gtk.VPaned vpaned2;
		private global::Gtk.Label labelPrecioConsulta;
		private global::Gtk.HPaned hpaned6;
		private global::Gtk.Label labelPrecio;
		private global::Gtk.Button buttonCancel;
		private global::Gtk.Button buttonOk;
		
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget punto.gui.ConsultaPrecioDialog
			this.Name = "punto.gui.ConsultaPrecioDialog";
			this.Title = global::Mono.Unix.Catalog.GetString ("Consultar Precio");
			this.WindowPosition = ((global::Gtk.WindowPosition)(1));
			this.Gravity = ((global::Gdk.Gravity)(5));
			// Internal child punto.gui.ConsultaPrecioDialog.VBox
			global::Gtk.VBox w1 = this.VBox;
			w1.Name = "dialog1_VBox";
			w1.BorderWidth = ((uint)(2));
			// Container child dialog1_VBox.Gtk.Box+BoxChild
			this.table2 = new global::Gtk.Table (((uint)(3)), ((uint)(2)), false);
			this.table2.Name = "table2";
			this.table2.RowSpacing = ((uint)(6));
			this.table2.ColumnSpacing = ((uint)(6));
			// Container child table2.Gtk.Table+TableChild
			this.entryCodigoDeBarra = new global::Gtk.Entry ();
			this.entryCodigoDeBarra.CanFocus = true;
			this.entryCodigoDeBarra.Name = "entryCodigoDeBarra";
			this.entryCodigoDeBarra.IsEditable = true;
			this.entryCodigoDeBarra.InvisibleChar = '●';
			this.table2.Add (this.entryCodigoDeBarra);
			global::Gtk.Table.TableChild w2 = ((global::Gtk.Table.TableChild)(this.table2 [this.entryCodigoDeBarra]));
			w2.LeftAttach = ((uint)(1));
			w2.RightAttach = ((uint)(2));
			w2.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.hpaned4 = new global::Gtk.HPaned ();
			this.hpaned4.CanFocus = true;
			this.hpaned4.Name = "hpaned4";
			this.hpaned4.Position = 10;
			// Container child hpaned4.Gtk.Paned+PanedChild
			this.labelConsulta = new global::Gtk.Label ();
			this.labelConsulta.Name = "labelConsulta";
			this.labelConsulta.LabelProp = global::Mono.Unix.Catalog.GetString ("Codigo de Barra: ");
			this.hpaned4.Add (this.labelConsulta);
			this.table2.Add (this.hpaned4);
			global::Gtk.Table.TableChild w4 = ((global::Gtk.Table.TableChild)(this.table2 [this.hpaned4]));
			w4.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.hpaned5 = new global::Gtk.HPaned ();
			this.hpaned5.CanFocus = true;
			this.hpaned5.Name = "hpaned5";
			this.hpaned5.Position = 10;
			// Container child hpaned5.Gtk.Paned+PanedChild
			this.vpaned2 = new global::Gtk.VPaned ();
			this.vpaned2.CanFocus = true;
			this.vpaned2.Name = "vpaned2";
			this.vpaned2.Position = 10;
			// Container child vpaned2.Gtk.Paned+PanedChild
			this.labelPrecioConsulta = new global::Gtk.Label ();
			this.labelPrecioConsulta.Name = "labelPrecioConsulta";
			this.vpaned2.Add (this.labelPrecioConsulta);
			this.hpaned5.Add (this.vpaned2);
			this.table2.Add (this.hpaned5);
			global::Gtk.Table.TableChild w7 = ((global::Gtk.Table.TableChild)(this.table2 [this.hpaned5]));
			w7.TopAttach = ((uint)(1));
			w7.BottomAttach = ((uint)(2));
			w7.LeftAttach = ((uint)(1));
			w7.RightAttach = ((uint)(2));
			// Container child table2.Gtk.Table+TableChild
			this.hpaned6 = new global::Gtk.HPaned ();
			this.hpaned6.CanFocus = true;
			this.hpaned6.Name = "hpaned6";
			this.hpaned6.Position = 10;
			// Container child hpaned6.Gtk.Paned+PanedChild
			this.labelPrecio = new global::Gtk.Label ();
			this.labelPrecio.Name = "labelPrecio";
			this.labelPrecio.Xalign = 0F;
			this.labelPrecio.LabelProp = global::Mono.Unix.Catalog.GetString ("       Precio: ");
			this.hpaned6.Add (this.labelPrecio);
			this.table2.Add (this.hpaned6);
			global::Gtk.Table.TableChild w9 = ((global::Gtk.Table.TableChild)(this.table2 [this.hpaned6]));
			w9.TopAttach = ((uint)(1));
			w9.BottomAttach = ((uint)(2));
			w1.Add (this.table2);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(w1 [this.table2]));
			w10.Position = 0;
			// Internal child punto.gui.ConsultaPrecioDialog.ActionArea
			global::Gtk.HButtonBox w11 = this.ActionArea;
			w11.Name = "dialog1_ActionArea";
			w11.Spacing = 10;
			w11.BorderWidth = ((uint)(5));
			w11.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(4));
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonCancel = new global::Gtk.Button ();
			this.buttonCancel.CanDefault = true;
			this.buttonCancel.CanFocus = true;
			this.buttonCancel.Name = "buttonCancel";
			this.buttonCancel.UseStock = true;
			this.buttonCancel.UseUnderline = true;
			this.buttonCancel.Label = "gtk-cancel";
			this.AddActionWidget (this.buttonCancel, -6);
			global::Gtk.ButtonBox.ButtonBoxChild w12 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w11 [this.buttonCancel]));
			w12.Expand = false;
			w12.Fill = false;
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonOk = new global::Gtk.Button ();
			this.buttonOk.CanDefault = true;
			this.buttonOk.CanFocus = true;
			this.buttonOk.Name = "buttonOk";
			this.buttonOk.UseStock = true;
			this.buttonOk.UseUnderline = true;
			this.buttonOk.Label = "gtk-ok";
			this.AddActionWidget (this.buttonOk, -5);
			global::Gtk.ButtonBox.ButtonBoxChild w13 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w11 [this.buttonOk]));
			w13.Position = 1;
			w13.Expand = false;
			w13.Fill = false;
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 300;
			this.Show ();
			this.entryCodigoDeBarra.TextInserted += new global::Gtk.TextInsertedHandler (this.OnEntryCodigoDeBarraTextInserted);
		}
	}
}
