
// This file has been generated by the GUI designer. Do not modify.
namespace punto.gui
{
	public partial class TarjetaEfectivoDialog
	{
		private global::Gtk.VBox dialog1_VBox1;
		private global::Gtk.Frame frame1;
		private global::Gtk.Alignment GtkAlignment2;
		private global::Gtk.VBox vbox2;
		private global::Gtk.Alignment alignment10;
		private global::Gtk.Alignment alignment11;
		private global::Gtk.HBox hbox1;
		private global::Gtk.Alignment alignment4;
		private global::Gtk.Label labeltotal;
		private global::Gtk.Label labeltotalcompra1;
		private global::Gtk.Alignment alignment5;
		private global::Gtk.Frame frame2;
		private global::Gtk.Alignment GtkAlignment3;
		private global::Gtk.Table table1;
		private global::Gtk.ComboBoxEntry comboboxentryTipoTarjeta;
		private global::Gtk.Entry entryMonto;
		private global::Gtk.Entry entryNroTransaccion;
		private global::Gtk.Label labelMonto;
		private global::Gtk.Label labelNroTransacción;
		private global::Gtk.Label labelTipoTarjeta;
		private global::Gtk.Label GtkLabel3;
		private global::Gtk.Frame frame3;
		private global::Gtk.Alignment GtkAlignment4;
		private global::Gtk.HBox hbox2;
		private global::Gtk.VBox vbox7;
		private global::Gtk.Alignment alignment12;
		private global::Gtk.Alignment alignment13;
		private global::Gtk.HBox hbox4;
		private global::Gtk.Label labelEfectivo;
		private global::Gtk.Entry entryPagoEfectivo;
		private global::Gtk.Alignment alignment16;
		private global::Gtk.HBox hbox6;
		private global::Gtk.Alignment alignment6;
		private global::Gtk.Alignment alignment7;
		private global::Gtk.Label GtkLabel7;
		private global::Gtk.HBox hbox7;
		private global::Gtk.Alignment alignment9;
		private global::Gtk.Button buttonPagar;
		private global::Gtk.Alignment alignment8;
		private global::Gtk.Label GtkLabel4;
		private global::Gtk.Button buttonOk;
		
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget punto.gui.TarjetaEfectivoDialog
			this.Name = "punto.gui.TarjetaEfectivoDialog";
			this.Title = global::Mono.Unix.Catalog.GetString ("Pago Tarjeta - Efectivo");
			this.WindowPosition = ((global::Gtk.WindowPosition)(1));
			// Internal child punto.gui.TarjetaEfectivoDialog.VBox
			global::Gtk.VBox w1 = this.VBox;
			w1.Name = "dialog1_VBox";
			w1.BorderWidth = ((uint)(2));
			// Container child dialog1_VBox.Gtk.Box+BoxChild
			this.dialog1_VBox1 = new global::Gtk.VBox ();
			this.dialog1_VBox1.Name = "dialog1_VBox1";
			this.dialog1_VBox1.BorderWidth = ((uint)(2));
			// Container child dialog1_VBox1.Gtk.Box+BoxChild
			this.frame1 = new global::Gtk.Frame ();
			this.frame1.Name = "frame1";
			this.frame1.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child frame1.Gtk.Container+ContainerChild
			this.GtkAlignment2 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.GtkAlignment2.Name = "GtkAlignment2";
			this.GtkAlignment2.LeftPadding = ((uint)(12));
			// Container child GtkAlignment2.Gtk.Container+ContainerChild
			this.vbox2 = new global::Gtk.VBox ();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.alignment10 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
			this.alignment10.Name = "alignment10";
			// Container child alignment10.Gtk.Container+ContainerChild
			this.alignment11 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
			this.alignment11.Name = "alignment11";
			this.alignment10.Add (this.alignment11);
			this.vbox2.Add (this.alignment10);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.alignment10]));
			w3.Position = 0;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.alignment4 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
			this.alignment4.Name = "alignment4";
			this.hbox1.Add (this.alignment4);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.alignment4]));
			w4.Position = 0;
			// Container child hbox1.Gtk.Box+BoxChild
			this.labeltotal = new global::Gtk.Label ();
			this.labeltotal.Name = "labeltotal";
			this.labeltotal.LabelProp = global::Mono.Unix.Catalog.GetString ("Total    :");
			this.hbox1.Add (this.labeltotal);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.labeltotal]));
			w5.Position = 1;
			w5.Expand = false;
			w5.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.labeltotalcompra1 = new global::Gtk.Label ();
			this.labeltotalcompra1.Name = "labeltotalcompra1";
			this.hbox1.Add (this.labeltotalcompra1);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.labeltotalcompra1]));
			w6.Position = 2;
			w6.Expand = false;
			w6.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.alignment5 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
			this.alignment5.Name = "alignment5";
			this.hbox1.Add (this.alignment5);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.alignment5]));
			w7.Position = 3;
			this.vbox2.Add (this.hbox1);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox1]));
			w8.Position = 1;
			w8.Expand = false;
			w8.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.frame2 = new global::Gtk.Frame ();
			this.frame2.Name = "frame2";
			this.frame2.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child frame2.Gtk.Container+ContainerChild
			this.GtkAlignment3 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.GtkAlignment3.Name = "GtkAlignment3";
			this.GtkAlignment3.LeftPadding = ((uint)(12));
			// Container child GtkAlignment3.Gtk.Container+ContainerChild
			this.table1 = new global::Gtk.Table (((uint)(3)), ((uint)(4)), false);
			this.table1.Name = "table1";
			this.table1.RowSpacing = ((uint)(6));
			this.table1.ColumnSpacing = ((uint)(6));
			// Container child table1.Gtk.Table+TableChild
			this.comboboxentryTipoTarjeta = global::Gtk.ComboBoxEntry.NewText ();
			this.comboboxentryTipoTarjeta.Name = "comboboxentryTipoTarjeta";
			this.table1.Add (this.comboboxentryTipoTarjeta);
			global::Gtk.Table.TableChild w9 = ((global::Gtk.Table.TableChild)(this.table1 [this.comboboxentryTipoTarjeta]));
			w9.LeftAttach = ((uint)(2));
			w9.RightAttach = ((uint)(3));
			w9.XOptions = ((global::Gtk.AttachOptions)(4));
			w9.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.entryMonto = new global::Gtk.Entry ();
			this.entryMonto.CanFocus = true;
			this.entryMonto.Name = "entryMonto";
			this.entryMonto.IsEditable = true;
			this.entryMonto.InvisibleChar = '●';
			this.table1.Add (this.entryMonto);
			global::Gtk.Table.TableChild w10 = ((global::Gtk.Table.TableChild)(this.table1 [this.entryMonto]));
			w10.TopAttach = ((uint)(2));
			w10.BottomAttach = ((uint)(3));
			w10.LeftAttach = ((uint)(2));
			w10.RightAttach = ((uint)(3));
			w10.XOptions = ((global::Gtk.AttachOptions)(4));
			w10.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.entryNroTransaccion = new global::Gtk.Entry ();
			this.entryNroTransaccion.CanFocus = true;
			this.entryNroTransaccion.Name = "entryNroTransaccion";
			this.entryNroTransaccion.IsEditable = true;
			this.entryNroTransaccion.InvisibleChar = '●';
			this.table1.Add (this.entryNroTransaccion);
			global::Gtk.Table.TableChild w11 = ((global::Gtk.Table.TableChild)(this.table1 [this.entryNroTransaccion]));
			w11.TopAttach = ((uint)(1));
			w11.BottomAttach = ((uint)(2));
			w11.LeftAttach = ((uint)(2));
			w11.RightAttach = ((uint)(3));
			w11.XOptions = ((global::Gtk.AttachOptions)(4));
			w11.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.labelMonto = new global::Gtk.Label ();
			this.labelMonto.Name = "labelMonto";
			this.labelMonto.Xalign = 0F;
			this.labelMonto.LabelProp = global::Mono.Unix.Catalog.GetString ("Monto:");
			this.table1.Add (this.labelMonto);
			global::Gtk.Table.TableChild w12 = ((global::Gtk.Table.TableChild)(this.table1 [this.labelMonto]));
			w12.TopAttach = ((uint)(2));
			w12.BottomAttach = ((uint)(3));
			w12.LeftAttach = ((uint)(1));
			w12.RightAttach = ((uint)(2));
			w12.XOptions = ((global::Gtk.AttachOptions)(4));
			w12.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.labelNroTransacción = new global::Gtk.Label ();
			this.labelNroTransacción.Name = "labelNroTransacción";
			this.labelNroTransacción.Xalign = 0F;
			this.labelNroTransacción.LabelProp = global::Mono.Unix.Catalog.GetString ("Nro Transacción:");
			this.table1.Add (this.labelNroTransacción);
			global::Gtk.Table.TableChild w13 = ((global::Gtk.Table.TableChild)(this.table1 [this.labelNroTransacción]));
			w13.TopAttach = ((uint)(1));
			w13.BottomAttach = ((uint)(2));
			w13.LeftAttach = ((uint)(1));
			w13.RightAttach = ((uint)(2));
			w13.XOptions = ((global::Gtk.AttachOptions)(4));
			w13.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.labelTipoTarjeta = new global::Gtk.Label ();
			this.labelTipoTarjeta.Name = "labelTipoTarjeta";
			this.labelTipoTarjeta.Xalign = 0F;
			this.labelTipoTarjeta.LabelProp = global::Mono.Unix.Catalog.GetString ("Tipo Tarjeta:");
			this.table1.Add (this.labelTipoTarjeta);
			global::Gtk.Table.TableChild w14 = ((global::Gtk.Table.TableChild)(this.table1 [this.labelTipoTarjeta]));
			w14.LeftAttach = ((uint)(1));
			w14.RightAttach = ((uint)(2));
			w14.XOptions = ((global::Gtk.AttachOptions)(4));
			w14.YOptions = ((global::Gtk.AttachOptions)(4));
			this.GtkAlignment3.Add (this.table1);
			this.frame2.Add (this.GtkAlignment3);
			this.GtkLabel3 = new global::Gtk.Label ();
			this.GtkLabel3.Name = "GtkLabel3";
			this.GtkLabel3.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Tarjeta</b>");
			this.GtkLabel3.UseMarkup = true;
			this.frame2.LabelWidget = this.GtkLabel3;
			this.vbox2.Add (this.frame2);
			global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.frame2]));
			w17.Position = 2;
			w17.Expand = false;
			w17.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.frame3 = new global::Gtk.Frame ();
			this.frame3.Name = "frame3";
			this.frame3.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child frame3.Gtk.Container+ContainerChild
			this.GtkAlignment4 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.GtkAlignment4.Name = "GtkAlignment4";
			this.GtkAlignment4.LeftPadding = ((uint)(12));
			// Container child GtkAlignment4.Gtk.Container+ContainerChild
			this.hbox2 = new global::Gtk.HBox ();
			this.hbox2.Name = "hbox2";
			this.hbox2.Spacing = 6;
			// Container child hbox2.Gtk.Box+BoxChild
			this.vbox7 = new global::Gtk.VBox ();
			this.vbox7.Name = "vbox7";
			this.vbox7.Spacing = 6;
			// Container child vbox7.Gtk.Box+BoxChild
			this.alignment12 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
			this.alignment12.Name = "alignment12";
			// Container child alignment12.Gtk.Container+ContainerChild
			this.alignment13 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
			this.alignment13.Name = "alignment13";
			this.alignment12.Add (this.alignment13);
			this.vbox7.Add (this.alignment12);
			global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.vbox7 [this.alignment12]));
			w19.Position = 0;
			// Container child vbox7.Gtk.Box+BoxChild
			this.hbox4 = new global::Gtk.HBox ();
			this.hbox4.Name = "hbox4";
			this.hbox4.Spacing = 6;
			// Container child hbox4.Gtk.Box+BoxChild
			this.labelEfectivo = new global::Gtk.Label ();
			this.labelEfectivo.Name = "labelEfectivo";
			this.labelEfectivo.LabelProp = global::Mono.Unix.Catalog.GetString ("Efectivo:");
			this.hbox4.Add (this.labelEfectivo);
			global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.labelEfectivo]));
			w20.Position = 0;
			w20.Expand = false;
			w20.Fill = false;
			// Container child hbox4.Gtk.Box+BoxChild
			this.entryPagoEfectivo = new global::Gtk.Entry ();
			this.entryPagoEfectivo.WidthRequest = 106;
			this.entryPagoEfectivo.CanFocus = true;
			this.entryPagoEfectivo.Name = "entryPagoEfectivo";
			this.entryPagoEfectivo.IsEditable = true;
			this.entryPagoEfectivo.InvisibleChar = '●';
			this.hbox4.Add (this.entryPagoEfectivo);
			global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.entryPagoEfectivo]));
			w21.Position = 1;
			// Container child hbox4.Gtk.Box+BoxChild
			this.alignment16 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
			this.alignment16.Name = "alignment16";
			this.hbox4.Add (this.alignment16);
			global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.alignment16]));
			w22.Position = 2;
			this.vbox7.Add (this.hbox4);
			global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.vbox7 [this.hbox4]));
			w23.Position = 1;
			w23.Expand = false;
			w23.Fill = false;
			// Container child vbox7.Gtk.Box+BoxChild
			this.hbox6 = new global::Gtk.HBox ();
			this.hbox6.Name = "hbox6";
			this.hbox6.Spacing = 6;
			// Container child hbox6.Gtk.Box+BoxChild
			this.alignment6 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
			this.alignment6.Name = "alignment6";
			this.hbox6.Add (this.alignment6);
			global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.alignment6]));
			w24.Position = 0;
			// Container child hbox6.Gtk.Box+BoxChild
			this.alignment7 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
			this.alignment7.Name = "alignment7";
			this.hbox6.Add (this.alignment7);
			global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.alignment7]));
			w25.Position = 1;
			this.vbox7.Add (this.hbox6);
			global::Gtk.Box.BoxChild w26 = ((global::Gtk.Box.BoxChild)(this.vbox7 [this.hbox6]));
			w26.PackType = ((global::Gtk.PackType)(1));
			w26.Position = 2;
			this.hbox2.Add (this.vbox7);
			global::Gtk.Box.BoxChild w27 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.vbox7]));
			w27.PackType = ((global::Gtk.PackType)(1));
			w27.Position = 0;
			this.GtkAlignment4.Add (this.hbox2);
			this.frame3.Add (this.GtkAlignment4);
			this.GtkLabel7 = new global::Gtk.Label ();
			this.GtkLabel7.Name = "GtkLabel7";
			this.GtkLabel7.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Efectivo</b>");
			this.GtkLabel7.UseMarkup = true;
			this.frame3.LabelWidget = this.GtkLabel7;
			this.vbox2.Add (this.frame3);
			global::Gtk.Box.BoxChild w30 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.frame3]));
			w30.Position = 3;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbox7 = new global::Gtk.HBox ();
			this.hbox7.Name = "hbox7";
			this.hbox7.Spacing = 6;
			// Container child hbox7.Gtk.Box+BoxChild
			this.alignment9 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
			this.alignment9.Name = "alignment9";
			this.hbox7.Add (this.alignment9);
			global::Gtk.Box.BoxChild w31 = ((global::Gtk.Box.BoxChild)(this.hbox7 [this.alignment9]));
			w31.Position = 0;
			// Container child hbox7.Gtk.Box+BoxChild
			this.buttonPagar = new global::Gtk.Button ();
			this.buttonPagar.CanFocus = true;
			this.buttonPagar.Name = "buttonPagar";
			this.buttonPagar.UseUnderline = true;
			// Container child buttonPagar.Gtk.Container+ContainerChild
			global::Gtk.Alignment w32 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w33 = new global::Gtk.HBox ();
			w33.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w34 = new global::Gtk.Image ();
			w34.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-save-as", global::Gtk.IconSize.Menu);
			w33.Add (w34);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w36 = new global::Gtk.Label ();
			w36.LabelProp = global::Mono.Unix.Catalog.GetString ("Guardar Venta");
			w36.UseUnderline = true;
			w33.Add (w36);
			w32.Add (w33);
			this.buttonPagar.Add (w32);
			this.hbox7.Add (this.buttonPagar);
			global::Gtk.Box.BoxChild w40 = ((global::Gtk.Box.BoxChild)(this.hbox7 [this.buttonPagar]));
			w40.Position = 1;
			w40.Expand = false;
			w40.Fill = false;
			// Container child hbox7.Gtk.Box+BoxChild
			this.alignment8 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
			this.alignment8.Name = "alignment8";
			this.hbox7.Add (this.alignment8);
			global::Gtk.Box.BoxChild w41 = ((global::Gtk.Box.BoxChild)(this.hbox7 [this.alignment8]));
			w41.Position = 2;
			this.vbox2.Add (this.hbox7);
			global::Gtk.Box.BoxChild w42 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox7]));
			w42.PackType = ((global::Gtk.PackType)(1));
			w42.Position = 4;
			w42.Expand = false;
			w42.Fill = false;
			this.GtkAlignment2.Add (this.vbox2);
			this.frame1.Add (this.GtkAlignment2);
			this.GtkLabel4 = new global::Gtk.Label ();
			this.GtkLabel4.Name = "GtkLabel4";
			this.GtkLabel4.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Complete los siguientes campos</b>");
			this.GtkLabel4.UseMarkup = true;
			this.frame1.LabelWidget = this.GtkLabel4;
			this.dialog1_VBox1.Add (this.frame1);
			global::Gtk.Box.BoxChild w45 = ((global::Gtk.Box.BoxChild)(this.dialog1_VBox1 [this.frame1]));
			w45.Position = 0;
			w1.Add (this.dialog1_VBox1);
			global::Gtk.Box.BoxChild w46 = ((global::Gtk.Box.BoxChild)(w1 [this.dialog1_VBox1]));
			w46.Position = 0;
			// Internal child punto.gui.TarjetaEfectivoDialog.ActionArea
			global::Gtk.HButtonBox w47 = this.ActionArea;
			w47.Name = "dialog1_ActionArea";
			w47.Spacing = 10;
			w47.BorderWidth = ((uint)(5));
			w47.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(4));
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonOk = new global::Gtk.Button ();
			this.buttonOk.CanDefault = true;
			this.buttonOk.CanFocus = true;
			this.buttonOk.Name = "buttonOk";
			this.buttonOk.UseUnderline = true;
			// Container child buttonOk.Gtk.Container+ContainerChild
			global::Gtk.Alignment w48 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w49 = new global::Gtk.HBox ();
			w49.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w50 = new global::Gtk.Image ();
			w50.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-quit", global::Gtk.IconSize.Menu);
			w49.Add (w50);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w52 = new global::Gtk.Label ();
			w52.LabelProp = global::Mono.Unix.Catalog.GetString ("Salir");
			w52.UseUnderline = true;
			w49.Add (w52);
			w48.Add (w49);
			this.buttonOk.Add (w48);
			this.AddActionWidget (this.buttonOk, -7);
			global::Gtk.ButtonBox.ButtonBoxChild w56 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w47 [this.buttonOk]));
			w56.Expand = false;
			w56.Fill = false;
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 376;
			this.Show ();
			this.buttonPagar.Clicked += new global::System.EventHandler (this.OnButtonPagarClicked);
		}
	}
}
