
// This file has been generated by the GUI designer. Do not modify.
namespace punto.gui
{
	public partial class basedatosdialog
	{
		private global::Gtk.VBox dialog1_VBox1;
		private global::Gtk.Table table1;
		private global::Gtk.Button BotonProbarConexion;
		private global::Gtk.Entry entryBaseDatos;
		private global::Gtk.Entry entryContraseña;
		private global::Gtk.Entry entryServidor;
		private global::Gtk.Entry entryUsuario;
		private global::Gtk.Label labelBaseDatos;
		private global::Gtk.Label labelContraseña;
		private global::Gtk.Label labelProbarConexion;
		private global::Gtk.Label labelServidor;
		private global::Gtk.Label labelUsuario;
		private global::Gtk.Button buttonCancel;
		private global::Gtk.Button buttonOk;
		
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget punto.gui.basedatosdialog
			this.Name = "punto.gui.basedatosdialog";
			this.Title = global::Mono.Unix.Catalog.GetString ("Conectar a Base de Datos");
			this.WindowPosition = ((global::Gtk.WindowPosition)(1));
			// Internal child punto.gui.basedatosdialog.VBox
			global::Gtk.VBox w1 = this.VBox;
			w1.Name = "dialog1_VBox";
			w1.BorderWidth = ((uint)(2));
			// Container child dialog1_VBox.Gtk.Box+BoxChild
			this.dialog1_VBox1 = new global::Gtk.VBox ();
			this.dialog1_VBox1.Name = "dialog1_VBox1";
			this.dialog1_VBox1.BorderWidth = ((uint)(2));
			// Container child dialog1_VBox1.Gtk.Box+BoxChild
			this.table1 = new global::Gtk.Table (((uint)(6)), ((uint)(2)), false);
			this.table1.Name = "table1";
			this.table1.RowSpacing = ((uint)(6));
			this.table1.ColumnSpacing = ((uint)(6));
			// Container child table1.Gtk.Table+TableChild
			this.BotonProbarConexion = new global::Gtk.Button ();
			this.BotonProbarConexion.CanFocus = true;
			this.BotonProbarConexion.Name = "BotonProbarConexion";
			this.BotonProbarConexion.UseUnderline = true;
			this.BotonProbarConexion.Label = global::Mono.Unix.Catalog.GetString ("Probar Conexión");
			this.table1.Add (this.BotonProbarConexion);
			global::Gtk.Table.TableChild w2 = ((global::Gtk.Table.TableChild)(this.table1 [this.BotonProbarConexion]));
			w2.TopAttach = ((uint)(4));
			w2.BottomAttach = ((uint)(5));
			w2.LeftAttach = ((uint)(1));
			w2.RightAttach = ((uint)(2));
			w2.XOptions = ((global::Gtk.AttachOptions)(4));
			w2.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.entryBaseDatos = new global::Gtk.Entry ();
			this.entryBaseDatos.CanFocus = true;
			this.entryBaseDatos.Name = "entryBaseDatos";
			this.entryBaseDatos.IsEditable = true;
			this.entryBaseDatos.InvisibleChar = '●';
			this.table1.Add (this.entryBaseDatos);
			global::Gtk.Table.TableChild w3 = ((global::Gtk.Table.TableChild)(this.table1 [this.entryBaseDatos]));
			w3.TopAttach = ((uint)(1));
			w3.BottomAttach = ((uint)(2));
			w3.LeftAttach = ((uint)(1));
			w3.RightAttach = ((uint)(2));
			w3.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.entryContraseña = new global::Gtk.Entry ();
			this.entryContraseña.CanFocus = true;
			this.entryContraseña.Name = "entryContraseña";
			this.entryContraseña.IsEditable = true;
			this.entryContraseña.Visibility = false;
			this.entryContraseña.InvisibleChar = '●';
			this.table1.Add (this.entryContraseña);
			global::Gtk.Table.TableChild w4 = ((global::Gtk.Table.TableChild)(this.table1 [this.entryContraseña]));
			w4.TopAttach = ((uint)(3));
			w4.BottomAttach = ((uint)(4));
			w4.LeftAttach = ((uint)(1));
			w4.RightAttach = ((uint)(2));
			w4.XOptions = ((global::Gtk.AttachOptions)(4));
			w4.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.entryServidor = new global::Gtk.Entry ();
			this.entryServidor.CanFocus = true;
			this.entryServidor.Name = "entryServidor";
			this.entryServidor.IsEditable = true;
			this.entryServidor.InvisibleChar = '●';
			this.table1.Add (this.entryServidor);
			global::Gtk.Table.TableChild w5 = ((global::Gtk.Table.TableChild)(this.table1 [this.entryServidor]));
			w5.LeftAttach = ((uint)(1));
			w5.RightAttach = ((uint)(2));
			w5.XOptions = ((global::Gtk.AttachOptions)(4));
			w5.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.entryUsuario = new global::Gtk.Entry ();
			this.entryUsuario.CanFocus = true;
			this.entryUsuario.Name = "entryUsuario";
			this.entryUsuario.IsEditable = true;
			this.entryUsuario.InvisibleChar = '●';
			this.table1.Add (this.entryUsuario);
			global::Gtk.Table.TableChild w6 = ((global::Gtk.Table.TableChild)(this.table1 [this.entryUsuario]));
			w6.TopAttach = ((uint)(2));
			w6.BottomAttach = ((uint)(3));
			w6.LeftAttach = ((uint)(1));
			w6.RightAttach = ((uint)(2));
			w6.XOptions = ((global::Gtk.AttachOptions)(4));
			w6.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.labelBaseDatos = new global::Gtk.Label ();
			this.labelBaseDatos.Name = "labelBaseDatos";
			this.labelBaseDatos.Xalign = 0F;
			this.labelBaseDatos.LabelProp = global::Mono.Unix.Catalog.GetString ("Base de Datos:");
			this.table1.Add (this.labelBaseDatos);
			global::Gtk.Table.TableChild w7 = ((global::Gtk.Table.TableChild)(this.table1 [this.labelBaseDatos]));
			w7.TopAttach = ((uint)(1));
			w7.BottomAttach = ((uint)(2));
			w7.XOptions = ((global::Gtk.AttachOptions)(4));
			w7.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.labelContraseña = new global::Gtk.Label ();
			this.labelContraseña.Name = "labelContraseña";
			this.labelContraseña.Xalign = 0F;
			this.labelContraseña.LabelProp = global::Mono.Unix.Catalog.GetString ("Contraseña:");
			this.table1.Add (this.labelContraseña);
			global::Gtk.Table.TableChild w8 = ((global::Gtk.Table.TableChild)(this.table1 [this.labelContraseña]));
			w8.TopAttach = ((uint)(3));
			w8.BottomAttach = ((uint)(4));
			w8.XOptions = ((global::Gtk.AttachOptions)(4));
			w8.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.labelProbarConexion = new global::Gtk.Label ();
			this.labelProbarConexion.Name = "labelProbarConexion";
			this.labelProbarConexion.LabelProp = global::Mono.Unix.Catalog.GetString ("Probar conexión");
			this.table1.Add (this.labelProbarConexion);
			global::Gtk.Table.TableChild w9 = ((global::Gtk.Table.TableChild)(this.table1 [this.labelProbarConexion]));
			w9.TopAttach = ((uint)(5));
			w9.BottomAttach = ((uint)(6));
			w9.LeftAttach = ((uint)(1));
			w9.RightAttach = ((uint)(2));
			w9.XOptions = ((global::Gtk.AttachOptions)(4));
			w9.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.labelServidor = new global::Gtk.Label ();
			this.labelServidor.Name = "labelServidor";
			this.labelServidor.Xalign = 0F;
			this.labelServidor.LabelProp = global::Mono.Unix.Catalog.GetString ("Servidor:");
			this.table1.Add (this.labelServidor);
			global::Gtk.Table.TableChild w10 = ((global::Gtk.Table.TableChild)(this.table1 [this.labelServidor]));
			w10.XOptions = ((global::Gtk.AttachOptions)(4));
			w10.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.labelUsuario = new global::Gtk.Label ();
			this.labelUsuario.Name = "labelUsuario";
			this.labelUsuario.Xalign = 0F;
			this.labelUsuario.LabelProp = global::Mono.Unix.Catalog.GetString ("Usuario:");
			this.table1.Add (this.labelUsuario);
			global::Gtk.Table.TableChild w11 = ((global::Gtk.Table.TableChild)(this.table1 [this.labelUsuario]));
			w11.TopAttach = ((uint)(2));
			w11.BottomAttach = ((uint)(3));
			w11.XOptions = ((global::Gtk.AttachOptions)(4));
			w11.YOptions = ((global::Gtk.AttachOptions)(4));
			this.dialog1_VBox1.Add (this.table1);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.dialog1_VBox1 [this.table1]));
			w12.Position = 0;
			w12.Expand = false;
			w12.Fill = false;
			w1.Add (this.dialog1_VBox1);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(w1 [this.dialog1_VBox1]));
			w13.Position = 0;
			w13.Expand = false;
			w13.Fill = false;
			// Internal child punto.gui.basedatosdialog.ActionArea
			global::Gtk.HButtonBox w14 = this.ActionArea;
			w14.Name = "dialog1_ActionArea";
			w14.Spacing = 10;
			w14.BorderWidth = ((uint)(5));
			w14.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(4));
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonCancel = new global::Gtk.Button ();
			this.buttonCancel.CanDefault = true;
			this.buttonCancel.CanFocus = true;
			this.buttonCancel.Name = "buttonCancel";
			this.buttonCancel.UseUnderline = true;
			this.buttonCancel.Label = global::Mono.Unix.Catalog.GetString ("_Cancelar");
			this.AddActionWidget (this.buttonCancel, -6);
			global::Gtk.ButtonBox.ButtonBoxChild w15 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w14 [this.buttonCancel]));
			w15.Expand = false;
			w15.Fill = false;
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonOk = new global::Gtk.Button ();
			this.buttonOk.CanDefault = true;
			this.buttonOk.CanFocus = true;
			this.buttonOk.Name = "buttonOk";
			this.buttonOk.UseStock = true;
			this.buttonOk.UseUnderline = true;
			this.buttonOk.Label = "gtk-ok";
			this.AddActionWidget (this.buttonOk, -5);
			global::Gtk.ButtonBox.ButtonBoxChild w16 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w14 [this.buttonOk]));
			w16.Position = 1;
			w16.Expand = false;
			w16.Fill = false;
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 300;
			this.Show ();
			this.BotonProbarConexion.Clicked += new global::System.EventHandler (this.OnProbarConexionClicked);
			this.buttonOk.Clicked += new global::System.EventHandler (this.OnGuardarClicked);
		}
	}
}
