
// This file has been generated by the GUI designer. Do not modify.
namespace punto.gui
{
	public partial class PrincipalWindow
	{
		private global::Gtk.UIManager UIManager;
		private global::Gtk.Action ProductosAction;
		private global::Gtk.Action AgregarFamiliaAction;
		private global::Gtk.Action SesionAction;
		private global::Gtk.Action RegistrarModificarAction;
		private global::Gtk.Action CerrarAction;
		private global::Gtk.VBox vbox2;
		private global::Gtk.MenuBar menubar1;
		
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget punto.gui.PrincipalWindow
			this.UIManager = new global::Gtk.UIManager ();
			global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup ("Default");
			this.ProductosAction = new global::Gtk.Action ("ProductosAction", global::Mono.Unix.Catalog.GetString ("Productos"), null, null);
			this.ProductosAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Productos");
			w1.Add (this.ProductosAction, null);
			this.AgregarFamiliaAction = new global::Gtk.Action ("AgregarFamiliaAction", global::Mono.Unix.Catalog.GetString ("Agregar Familia"), null, null);
			this.AgregarFamiliaAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Familia de productos");
			w1.Add (this.AgregarFamiliaAction, null);
			this.SesionAction = new global::Gtk.Action ("SesionAction", global::Mono.Unix.Catalog.GetString ("Sesion"), null, null);
			this.SesionAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Sesion");
			w1.Add (this.SesionAction, null);
			this.RegistrarModificarAction = new global::Gtk.Action ("RegistrarModificarAction", global::Mono.Unix.Catalog.GetString ("Registrar/Modificar"), null, null);
			this.RegistrarModificarAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Ingresar/Modificar");
			w1.Add (this.RegistrarModificarAction, null);
			this.CerrarAction = new global::Gtk.Action ("CerrarAction", global::Mono.Unix.Catalog.GetString ("Cerrar"), null, null);
			this.CerrarAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Cerrar");
			w1.Add (this.CerrarAction, null);
			this.UIManager.InsertActionGroup (w1, 0);
			this.AddAccelGroup (this.UIManager.AccelGroup);
			this.Name = "punto.gui.PrincipalWindow";
			this.Title = global::Mono.Unix.Catalog.GetString ("MiniMarket \"El Coke\"");
			this.WindowPosition = ((global::Gtk.WindowPosition)(1));
			// Container child punto.gui.PrincipalWindow.Gtk.Container+ContainerChild
			this.vbox2 = new global::Gtk.VBox ();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.UIManager.AddUiFromString ("<ui><menubar name='menubar1'><menu name='SesionAction' action='SesionAction'><menuitem name='CerrarAction' action='CerrarAction'/></menu><menu name='ProductosAction' action='ProductosAction'><menuitem name='AgregarFamiliaAction' action='AgregarFamiliaAction'/><menuitem name='RegistrarModificarAction' action='RegistrarModificarAction'/></menu></menubar></ui>");
			this.menubar1 = ((global::Gtk.MenuBar)(this.UIManager.GetWidget ("/menubar1")));
			this.menubar1.Name = "menubar1";
			this.vbox2.Add (this.menubar1);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.menubar1]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			this.Add (this.vbox2);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 731;
			this.DefaultHeight = 479;
			this.Show ();
			this.AgregarFamiliaAction.Activated += new global::System.EventHandler (this.OnFamiliaDeProductosActionActivated);
			this.RegistrarModificarAction.Activated += new global::System.EventHandler (this.OnIngresarModificarProductosActionActivated);
		}
	}
}
