
// This file has been generated by the GUI designer. Do not modify.
namespace punto.gui
{
	public partial class PrincipalWindow
	{
		private global::Gtk.UIManager UIManager;
		private global::Gtk.Action ProductosAction;
		private global::Gtk.Action AgregarFamiliaAction;
		private global::Gtk.Action SesionAction;
		private global::Gtk.Action RegistrarModificarAction;
		private global::Gtk.Action CerrarAction;
		private global::Gtk.Action InicioSesionAction;
		private global::Gtk.Action UsuariosAction;
		private global::Gtk.Action RegistrarModificarAction1;
		private global::Gtk.VBox vbox3;
		private global::Gtk.MenuBar BarraMenu;
		private global::Gtk.HBox hbox3;
		private global::Gtk.VPaned vpaned2;
		private global::Gtk.HPaned hpaned14;
		private global::Gtk.VBox vbox4;
		private global::Gtk.Table table2;
		private global::Gtk.Alignment alignment7;
		private global::Gtk.Alignment alignment8;
		private global::Gtk.Alignment alignment9;
		private global::Gtk.HPaned hpaned7;
		private global::Gtk.VPaned vpaned10;
		private global::Gtk.Button buttonVender;
		private global::Gtk.HPaned hpaned15;
		
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget punto.gui.PrincipalWindow
			this.UIManager = new global::Gtk.UIManager ();
			global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup ("Default");
			this.ProductosAction = new global::Gtk.Action ("ProductosAction", global::Mono.Unix.Catalog.GetString ("Productos"), null, null);
			this.ProductosAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Productos");
			w1.Add (this.ProductosAction, null);
			this.AgregarFamiliaAction = new global::Gtk.Action ("AgregarFamiliaAction", global::Mono.Unix.Catalog.GetString ("Agregar Familia"), null, null);
			this.AgregarFamiliaAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Familia de productos");
			w1.Add (this.AgregarFamiliaAction, null);
			this.SesionAction = new global::Gtk.Action ("SesionAction", global::Mono.Unix.Catalog.GetString ("Sesion"), null, null);
			this.SesionAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Sesion");
			w1.Add (this.SesionAction, null);
			this.RegistrarModificarAction = new global::Gtk.Action ("RegistrarModificarAction", global::Mono.Unix.Catalog.GetString ("Registrar/Modificar"), null, null);
			this.RegistrarModificarAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Ingresar/Modificar");
			w1.Add (this.RegistrarModificarAction, null);
			this.CerrarAction = new global::Gtk.Action ("CerrarAction", global::Mono.Unix.Catalog.GetString ("Cerrar"), null, null);
			this.CerrarAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Cerrar");
			w1.Add (this.CerrarAction, null);
			this.InicioSesionAction = new global::Gtk.Action ("InicioSesionAction", global::Mono.Unix.Catalog.GetString ("Inicio Sesion"), null, null);
			this.InicioSesionAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Inicio Sesion");
			w1.Add (this.InicioSesionAction, null);
			this.UsuariosAction = new global::Gtk.Action ("UsuariosAction", global::Mono.Unix.Catalog.GetString ("Usuarios"), null, null);
			this.UsuariosAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Usuarios");
			w1.Add (this.UsuariosAction, null);
			this.RegistrarModificarAction1 = new global::Gtk.Action ("RegistrarModificarAction1", global::Mono.Unix.Catalog.GetString ("Registrar/Modificar"), null, null);
			this.RegistrarModificarAction1.ShortLabel = global::Mono.Unix.Catalog.GetString ("Registrar/Modificar");
			w1.Add (this.RegistrarModificarAction1, null);
			this.UIManager.InsertActionGroup (w1, 0);
			this.AddAccelGroup (this.UIManager.AccelGroup);
			this.Name = "punto.gui.PrincipalWindow";
			this.Title = global::Mono.Unix.Catalog.GetString ("MiniMarket El Coke - Principal");
			this.WindowPosition = ((global::Gtk.WindowPosition)(1));
			// Container child punto.gui.PrincipalWindow.Gtk.Container+ContainerChild
			this.vbox3 = new global::Gtk.VBox ();
			this.vbox3.Name = "vbox3";
			this.vbox3.Spacing = 6;
			// Container child vbox3.Gtk.Box+BoxChild
			this.UIManager.AddUiFromString ("<ui><menubar name='BarraMenu'><menu name='SesionAction' action='SesionAction'><menuitem name='CerrarAction' action='CerrarAction'/></menu><menu name='ProductosAction' action='ProductosAction'><menuitem name='AgregarFamiliaAction' action='AgregarFamiliaAction'/><menuitem name='RegistrarModificarAction' action='RegistrarModificarAction'/></menu><menu name='UsuariosAction' action='UsuariosAction'><menuitem name='RegistrarModificarAction1' action='RegistrarModificarAction1'/></menu></menubar></ui>");
			this.BarraMenu = ((global::Gtk.MenuBar)(this.UIManager.GetWidget ("/BarraMenu")));
			this.BarraMenu.Name = "BarraMenu";
			this.vbox3.Add (this.BarraMenu);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.BarraMenu]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.hbox3 = new global::Gtk.HBox ();
			this.hbox3.Name = "hbox3";
			this.hbox3.Spacing = 6;
			// Container child hbox3.Gtk.Box+BoxChild
			this.vpaned2 = new global::Gtk.VPaned ();
			this.vpaned2.CanFocus = true;
			this.vpaned2.Name = "vpaned2";
			this.vpaned2.Position = 10;
			// Container child vpaned2.Gtk.Paned+PanedChild
			this.hpaned14 = new global::Gtk.HPaned ();
			this.hpaned14.CanFocus = true;
			this.hpaned14.Name = "hpaned14";
			this.hpaned14.Position = 10;
			// Container child hpaned14.Gtk.Paned+PanedChild
			this.vbox4 = new global::Gtk.VBox ();
			this.vbox4.Name = "vbox4";
			this.vbox4.Spacing = 6;
			// Container child vbox4.Gtk.Box+BoxChild
			this.table2 = new global::Gtk.Table (((uint)(3)), ((uint)(3)), false);
			this.table2.Name = "table2";
			this.table2.RowSpacing = ((uint)(6));
			this.table2.ColumnSpacing = ((uint)(6));
			// Container child table2.Gtk.Table+TableChild
			this.alignment7 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
			this.alignment7.Name = "alignment7";
			this.table2.Add (this.alignment7);
			global::Gtk.Table.TableChild w3 = ((global::Gtk.Table.TableChild)(this.table2 [this.alignment7]));
			w3.TopAttach = ((uint)(1));
			w3.BottomAttach = ((uint)(2));
			// Container child table2.Gtk.Table+TableChild
			this.alignment8 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
			this.alignment8.Name = "alignment8";
			this.table2.Add (this.alignment8);
			global::Gtk.Table.TableChild w4 = ((global::Gtk.Table.TableChild)(this.table2 [this.alignment8]));
			w4.TopAttach = ((uint)(2));
			w4.BottomAttach = ((uint)(3));
			// Container child table2.Gtk.Table+TableChild
			this.alignment9 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
			this.alignment9.Name = "alignment9";
			this.table2.Add (this.alignment9);
			global::Gtk.Table.TableChild w5 = ((global::Gtk.Table.TableChild)(this.table2 [this.alignment9]));
			w5.LeftAttach = ((uint)(1));
			w5.RightAttach = ((uint)(2));
			// Container child table2.Gtk.Table+TableChild
			this.hpaned7 = new global::Gtk.HPaned ();
			this.hpaned7.CanFocus = true;
			this.hpaned7.Name = "hpaned7";
			this.hpaned7.Position = 10;
			// Container child hpaned7.Gtk.Paned+PanedChild
			this.vpaned10 = new global::Gtk.VPaned ();
			this.vpaned10.CanFocus = true;
			this.vpaned10.Name = "vpaned10";
			this.vpaned10.Position = 10;
			// Container child vpaned10.Gtk.Paned+PanedChild
			this.buttonVender = new global::Gtk.Button ();
			this.buttonVender.CanFocus = true;
			this.buttonVender.Name = "buttonVender";
			this.buttonVender.UseUnderline = true;
			this.buttonVender.Label = global::Mono.Unix.Catalog.GetString ("VENDER");
			this.vpaned10.Add (this.buttonVender);
			this.hpaned7.Add (this.vpaned10);
			this.table2.Add (this.hpaned7);
			this.vbox4.Add (this.table2);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.table2]));
			w9.Position = 0;
			this.hpaned14.Add (this.vbox4);
			this.vpaned2.Add (this.hpaned14);
			this.hbox3.Add (this.vpaned2);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.vpaned2]));
			w12.Position = 0;
			// Container child hbox3.Gtk.Box+BoxChild
			this.hpaned15 = new global::Gtk.HPaned ();
			this.hpaned15.CanFocus = true;
			this.hpaned15.Name = "hpaned15";
			this.hpaned15.Position = 1;
			this.hbox3.Add (this.hpaned15);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.hpaned15]));
			w13.Position = 1;
			this.vbox3.Add (this.hbox3);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.hbox3]));
			w14.Position = 1;
			this.Add (this.vbox3);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 731;
			this.DefaultHeight = 479;
			this.Show ();
			this.AgregarFamiliaAction.Activated += new global::System.EventHandler (this.OnFamiliaDeProductosActionActivated);
			this.RegistrarModificarAction.Activated += new global::System.EventHandler (this.OnIngresarModificarProductosActionActivated);
			this.CerrarAction.Activated += new global::System.EventHandler (this.OnCerrarActionActivated);
			this.InicioSesionAction.Activated += new global::System.EventHandler (this.OnIniciarSesionActionActivated);
			this.RegistrarModificarAction1.Activated += new global::System.EventHandler (this.OnRegistrarModificarUsuarioActionActivated);
			this.buttonVender.Clicked += new global::System.EventHandler (this.OnButton27Clicked);
		}
	}
}
