
// This file has been generated by the GUI designer. Do not modify.
namespace punto.gui
{
	public partial class familiaproductosdialog
	{
		private global::Gtk.Table table1;
		private global::Gtk.Button añadir_button;
		private global::Gtk.ScrolledWindow GtkScrolledWindow;
		private global::Gtk.TreeView FamiliaProductosTreeview;
		private global::Gtk.HBox hbox4;
		private global::Gtk.Label labelFamilia;
		private global::Gtk.Entry entryFamilia;
		private global::Gtk.VBox vbox2;
		private global::Gtk.Button actualizar_button;
		private global::Gtk.Button quitar_button;
		private global::Gtk.Button buttonCerrar;
		
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget punto.gui.familiaproductosdialog
			this.Name = "punto.gui.familiaproductosdialog";
			this.Title = global::Mono.Unix.Catalog.GetString ("Agregar Familias de Productos");
			this.WindowPosition = ((global::Gtk.WindowPosition)(1));
			// Internal child punto.gui.familiaproductosdialog.VBox
			global::Gtk.VBox w1 = this.VBox;
			w1.Name = "dialog1_VBox";
			w1.BorderWidth = ((uint)(2));
			// Container child dialog1_VBox.Gtk.Box+BoxChild
			this.table1 = new global::Gtk.Table (((uint)(2)), ((uint)(2)), false);
			this.table1.Name = "table1";
			this.table1.RowSpacing = ((uint)(6));
			this.table1.ColumnSpacing = ((uint)(6));
			// Container child table1.Gtk.Table+TableChild
			this.añadir_button = new global::Gtk.Button ();
			this.añadir_button.CanFocus = true;
			this.añadir_button.Name = "añadir_button";
			this.añadir_button.UseUnderline = true;
			// Container child añadir_button.Gtk.Container+ContainerChild
			global::Gtk.Alignment w2 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w3 = new global::Gtk.HBox ();
			w3.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w4 = new global::Gtk.Image ();
			w4.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-add", global::Gtk.IconSize.Menu);
			w3.Add (w4);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w6 = new global::Gtk.Label ();
			w6.LabelProp = global::Mono.Unix.Catalog.GetString ("_Añadir");
			w6.UseUnderline = true;
			w3.Add (w6);
			w2.Add (w3);
			this.añadir_button.Add (w2);
			this.table1.Add (this.añadir_button);
			global::Gtk.Table.TableChild w10 = ((global::Gtk.Table.TableChild)(this.table1 [this.añadir_button]));
			w10.LeftAttach = ((uint)(1));
			w10.RightAttach = ((uint)(2));
			w10.XOptions = ((global::Gtk.AttachOptions)(4));
			w10.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.FamiliaProductosTreeview = new global::Gtk.TreeView ();
			this.FamiliaProductosTreeview.CanFocus = true;
			this.FamiliaProductosTreeview.Name = "FamiliaProductosTreeview";
			this.GtkScrolledWindow.Add (this.FamiliaProductosTreeview);
			this.table1.Add (this.GtkScrolledWindow);
			global::Gtk.Table.TableChild w12 = ((global::Gtk.Table.TableChild)(this.table1 [this.GtkScrolledWindow]));
			w12.TopAttach = ((uint)(1));
			w12.BottomAttach = ((uint)(2));
			// Container child table1.Gtk.Table+TableChild
			this.hbox4 = new global::Gtk.HBox ();
			this.hbox4.Name = "hbox4";
			this.hbox4.Spacing = 6;
			// Container child hbox4.Gtk.Box+BoxChild
			this.labelFamilia = new global::Gtk.Label ();
			this.labelFamilia.Name = "labelFamilia";
			this.labelFamilia.LabelProp = global::Mono.Unix.Catalog.GetString ("Familia");
			this.hbox4.Add (this.labelFamilia);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.labelFamilia]));
			w13.Position = 0;
			w13.Expand = false;
			w13.Fill = false;
			// Container child hbox4.Gtk.Box+BoxChild
			this.entryFamilia = new global::Gtk.Entry ();
			this.entryFamilia.CanFocus = true;
			this.entryFamilia.Name = "entryFamilia";
			this.entryFamilia.IsEditable = true;
			this.entryFamilia.MaxLength = 100;
			this.entryFamilia.InvisibleChar = '●';
			this.hbox4.Add (this.entryFamilia);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.entryFamilia]));
			w14.Position = 1;
			this.table1.Add (this.hbox4);
			global::Gtk.Table.TableChild w15 = ((global::Gtk.Table.TableChild)(this.table1 [this.hbox4]));
			w15.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.vbox2 = new global::Gtk.VBox ();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.actualizar_button = new global::Gtk.Button ();
			this.actualizar_button.CanFocus = true;
			this.actualizar_button.Name = "actualizar_button";
			this.actualizar_button.UseUnderline = true;
			// Container child actualizar_button.Gtk.Container+ContainerChild
			global::Gtk.Alignment w16 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w17 = new global::Gtk.HBox ();
			w17.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w18 = new global::Gtk.Image ();
			w18.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-refresh", global::Gtk.IconSize.Menu);
			w17.Add (w18);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w20 = new global::Gtk.Label ();
			w20.LabelProp = global::Mono.Unix.Catalog.GetString ("_Actualizar");
			w20.UseUnderline = true;
			w17.Add (w20);
			w16.Add (w17);
			this.actualizar_button.Add (w16);
			this.vbox2.Add (this.actualizar_button);
			global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.actualizar_button]));
			w24.Position = 0;
			w24.Expand = false;
			w24.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.quitar_button = new global::Gtk.Button ();
			this.quitar_button.CanFocus = true;
			this.quitar_button.Name = "quitar_button";
			this.quitar_button.UseUnderline = true;
			// Container child quitar_button.Gtk.Container+ContainerChild
			global::Gtk.Alignment w25 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w26 = new global::Gtk.HBox ();
			w26.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w27 = new global::Gtk.Image ();
			w27.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-delete", global::Gtk.IconSize.Menu);
			w26.Add (w27);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w29 = new global::Gtk.Label ();
			w29.LabelProp = global::Mono.Unix.Catalog.GetString ("_Quitar");
			w29.UseUnderline = true;
			w26.Add (w29);
			w25.Add (w26);
			this.quitar_button.Add (w25);
			this.vbox2.Add (this.quitar_button);
			global::Gtk.Box.BoxChild w33 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.quitar_button]));
			w33.Position = 1;
			w33.Expand = false;
			w33.Fill = false;
			this.table1.Add (this.vbox2);
			global::Gtk.Table.TableChild w34 = ((global::Gtk.Table.TableChild)(this.table1 [this.vbox2]));
			w34.TopAttach = ((uint)(1));
			w34.BottomAttach = ((uint)(2));
			w34.LeftAttach = ((uint)(1));
			w34.RightAttach = ((uint)(2));
			w34.XOptions = ((global::Gtk.AttachOptions)(4));
			w1.Add (this.table1);
			global::Gtk.Box.BoxChild w35 = ((global::Gtk.Box.BoxChild)(w1 [this.table1]));
			w35.Position = 0;
			// Internal child punto.gui.familiaproductosdialog.ActionArea
			global::Gtk.HButtonBox w36 = this.ActionArea;
			w36.Name = "dialog1_ActionArea";
			w36.Spacing = 10;
			w36.BorderWidth = ((uint)(5));
			w36.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(4));
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonCerrar = new global::Gtk.Button ();
			this.buttonCerrar.CanDefault = true;
			this.buttonCerrar.CanFocus = true;
			this.buttonCerrar.Name = "buttonCerrar";
			this.buttonCerrar.UseUnderline = true;
			// Container child buttonCerrar.Gtk.Container+ContainerChild
			global::Gtk.Alignment w37 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w38 = new global::Gtk.HBox ();
			w38.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w39 = new global::Gtk.Image ();
			w39.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-ok", global::Gtk.IconSize.Menu);
			w38.Add (w39);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w41 = new global::Gtk.Label ();
			w41.LabelProp = global::Mono.Unix.Catalog.GetString ("_Cerrar");
			w41.UseUnderline = true;
			w38.Add (w41);
			w37.Add (w38);
			this.buttonCerrar.Add (w37);
			this.AddActionWidget (this.buttonCerrar, -7);
			global::Gtk.ButtonBox.ButtonBoxChild w45 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w36 [this.buttonCerrar]));
			w45.Expand = false;
			w45.Fill = false;
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 300;
			this.actualizar_button.Hide ();
			this.Show ();
			this.actualizar_button.Clicked += new global::System.EventHandler (this.OnActualizarButtonClicked);
			this.quitar_button.Clicked += new global::System.EventHandler (this.OnQuitarButtonClicked);
			this.añadir_button.Clicked += new global::System.EventHandler (this.OnAgregarButtonClicked);
		}
	}
}
