
// This file has been generated by the GUI designer. Do not modify.
namespace punto.gui
{
	public partial class InicioSesionDialog
	{
		private global::Gtk.Button buttonCancel;
		private global::Gtk.Button buttonOk;
		
		protected virtual void Build ()
		{

		}
	}
}
