
// This file has been generated by the GUI designer. Do not modify.
namespace punto.code
{
	public partial class Usuario
	{
		public virtual void Build ()
		{
			// Action group punto.code.Usuario
		}
	}
}
